/**
 * World Lens — Seed Material Database
 *
 * Pre-populated engineering materials with full property sets.
 * USB Composite variants A-F, steel grades, concrete classes,
 * timber grades, and glass types.
 */

import type { MaterialDTU } from './types';

export const SEED_MATERIALS: MaterialDTU[] = [
  // ── USB Composite Variants ────────────────────────────────────
  {
    id: 'mat-usb-a',
    name: 'USB Composite A (Standard)',
    category: 'USB-composite',
    properties: {
      tensileStrength: 450,
      compressiveStrength: 380,
      shearStrength: 220,
      elasticModulus: 45,
      density: 1850,
      thermalConductivity: 0.35,
      thermalExpansionCoeff: 8e-6,
      meltingPoint: 850,
      fireResistanceHours: 2,
      corrosionResistance: 'high',
      fatigueLimit: 180,
      cost: 120,
    },
    creator: 'system',
    citations: 0,
    validationStatus: 'validated',
  },
  {
    id: 'mat-usb-b',
    name: 'USB Composite B (High Strength)',
    category: 'USB-composite',
    properties: {
      tensileStrength: 680,
      compressiveStrength: 550,
      shearStrength: 340,
      elasticModulus: 62,
      density: 2100,
      thermalConductivity: 0.42,
      thermalExpansionCoeff: 7e-6,
      meltingPoint: 920,
      fireResistanceHours: 3,
      corrosionResistance: 'extreme',
      fatigueLimit: 280,
      cost: 240,
    },
    creator: 'system',
    citations: 0,
    validationStatus: 'validated',
  },
  {
    id: 'mat-usb-c',
    name: 'USB Composite C (Lightweight)',
    category: 'USB-composite',
    properties: {
      tensileStrength: 350,
      compressiveStrength: 280,
      shearStrength: 170,
      elasticModulus: 38,
      density: 1450,
      thermalConductivity: 0.28,
      thermalExpansionCoeff: 9e-6,
      meltingPoint: 780,
      fireResistanceHours: 1.5,
      corrosionResistance: 'high',
      fatigueLimit: 140,
      cost: 95,
    },
    creator: 'system',
    citations: 0,
    validationStatus: 'validated',
  },
  {
    id: 'mat-usb-d',
    name: 'USB Composite D (Fire Resistant)',
    category: 'USB-composite',
    properties: {
      tensileStrength: 400,
      compressiveStrength: 350,
      shearStrength: 200,
      elasticModulus: 42,
      density: 2000,
      thermalConductivity: 0.18,
      thermalExpansionCoeff: 6e-6,
      meltingPoint: 1200,
      fireResistanceHours: 5,
      corrosionResistance: 'extreme',
      fatigueLimit: 160,
      cost: 280,
    },
    creator: 'system',
    citations: 0,
    validationStatus: 'validated',
  },
  {
    id: 'mat-usb-e',
    name: 'USB Composite E (Economy)',
    category: 'USB-composite',
    properties: {
      tensileStrength: 280,
      compressiveStrength: 240,
      shearStrength: 140,
      elasticModulus: 30,
      density: 1700,
      thermalConductivity: 0.40,
      thermalExpansionCoeff: 10e-6,
      meltingPoint: 720,
      fireResistanceHours: 1,
      corrosionResistance: 'moderate',
      fatigueLimit: 110,
      cost: 60,
    },
    creator: 'system',
    citations: 0,
    validationStatus: 'validated',
  },
  {
    id: 'mat-usb-f',
    name: 'USB Composite F (Ultra Performance)',
    category: 'USB-composite',
    properties: {
      tensileStrength: 900,
      compressiveStrength: 720,
      shearStrength: 450,
      elasticModulus: 80,
      density: 2400,
      thermalConductivity: 0.50,
      thermalExpansionCoeff: 5e-6,
      meltingPoint: 1100,
      fireResistanceHours: 4,
      corrosionResistance: 'extreme',
      fatigueLimit: 380,
      cost: 450,
    },
    creator: 'system',
    citations: 0,
    validationStatus: 'validated',
  },

  // ── Steel Grades ──────────────────────────────────────────────
  {
    id: 'mat-steel-a36',
    name: 'Steel A36 (Structural)',
    category: 'steel',
    properties: {
      tensileStrength: 400,
      compressiveStrength: 250,
      shearStrength: 230,
      elasticModulus: 200,
      density: 7850,
      thermalConductivity: 50,
      thermalExpansionCoeff: 12e-6,
      meltingPoint: 1540,
      fireResistanceHours: 0.5,
      corrosionResistance: 'low',
      fatigueLimit: 160,
      cost: 85,
    },
    creator: 'system',
    citations: 0,
    validationStatus: 'validated',
  },
  {
    id: 'mat-steel-a992',
    name: 'Steel A992 (High Strength)',
    category: 'steel',
    properties: {
      tensileStrength: 450,
      compressiveStrength: 345,
      shearStrength: 260,
      elasticModulus: 200,
      density: 7850,
      thermalConductivity: 50,
      thermalExpansionCoeff: 12e-6,
      meltingPoint: 1540,
      fireResistanceHours: 0.5,
      corrosionResistance: 'low',
      fatigueLimit: 190,
      cost: 110,
    },
    creator: 'system',
    citations: 0,
    validationStatus: 'validated',
  },
  {
    id: 'mat-steel-stainless-304',
    name: 'Stainless Steel 304',
    category: 'steel',
    properties: {
      tensileStrength: 515,
      compressiveStrength: 205,
      shearStrength: 310,
      elasticModulus: 193,
      density: 8000,
      thermalConductivity: 16,
      thermalExpansionCoeff: 17e-6,
      meltingPoint: 1450,
      fireResistanceHours: 1,
      corrosionResistance: 'extreme',
      fatigueLimit: 210,
      cost: 200,
    },
    creator: 'system',
    citations: 0,
    validationStatus: 'validated',
  },

  // ── Concrete Classes ──────────────────────────────────────────
  {
    id: 'mat-concrete-c20',
    name: 'Concrete C20/25',
    category: 'concrete',
    properties: {
      tensileStrength: 2.2,
      compressiveStrength: 20,
      shearStrength: 3,
      elasticModulus: 30,
      density: 2400,
      thermalConductivity: 1.7,
      thermalExpansionCoeff: 10e-6,
      meltingPoint: 1200,
      fireResistanceHours: 4,
      corrosionResistance: 'moderate',
      fatigueLimit: 8,
      cost: 35,
    },
    creator: 'system',
    citations: 0,
    validationStatus: 'validated',
  },
  {
    id: 'mat-concrete-c40',
    name: 'Concrete C40/50',
    category: 'concrete',
    properties: {
      tensileStrength: 3.5,
      compressiveStrength: 40,
      shearStrength: 5,
      elasticModulus: 35,
      density: 2450,
      thermalConductivity: 1.8,
      thermalExpansionCoeff: 10e-6,
      meltingPoint: 1200,
      fireResistanceHours: 4,
      corrosionResistance: 'moderate',
      fatigueLimit: 14,
      cost: 55,
    },
    creator: 'system',
    citations: 0,
    validationStatus: 'validated',
  },
  {
    id: 'mat-concrete-uhpc',
    name: 'Ultra-High Performance Concrete',
    category: 'concrete',
    properties: {
      tensileStrength: 8,
      compressiveStrength: 150,
      shearStrength: 15,
      elasticModulus: 50,
      density: 2500,
      thermalConductivity: 2.0,
      thermalExpansionCoeff: 10e-6,
      meltingPoint: 1200,
      fireResistanceHours: 5,
      corrosionResistance: 'high',
      fatigueLimit: 30,
      cost: 180,
    },
    creator: 'system',
    citations: 0,
    validationStatus: 'validated',
  },

  // ── Timber Grades ─────────────────────────────────────────────
  {
    id: 'mat-timber-softwood',
    name: 'Softwood (C24 Grade)',
    category: 'wood',
    properties: {
      tensileStrength: 14,
      compressiveStrength: 21,
      shearStrength: 4,
      elasticModulus: 11,
      density: 420,
      thermalConductivity: 0.13,
      thermalExpansionCoeff: 5e-6,
      meltingPoint: 300,
      fireResistanceHours: 0.5,
      corrosionResistance: 'low',
      fatigueLimit: 6,
      cost: 25,
    },
    creator: 'system',
    citations: 0,
    validationStatus: 'validated',
  },
  {
    id: 'mat-timber-glulam',
    name: 'Glued Laminated Timber (Glulam)',
    category: 'wood',
    properties: {
      tensileStrength: 24,
      compressiveStrength: 28,
      shearStrength: 6,
      elasticModulus: 13.5,
      density: 480,
      thermalConductivity: 0.14,
      thermalExpansionCoeff: 5e-6,
      meltingPoint: 300,
      fireResistanceHours: 1,
      corrosionResistance: 'low',
      fatigueLimit: 10,
      cost: 55,
    },
    creator: 'system',
    citations: 0,
    validationStatus: 'validated',
  },
  {
    id: 'mat-timber-clt',
    name: 'Cross-Laminated Timber (CLT)',
    category: 'wood',
    properties: {
      tensileStrength: 16,
      compressiveStrength: 24,
      shearStrength: 5.5,
      elasticModulus: 12,
      density: 500,
      thermalConductivity: 0.12,
      thermalExpansionCoeff: 5e-6,
      meltingPoint: 300,
      fireResistanceHours: 1.5,
      corrosionResistance: 'low',
      fatigueLimit: 8,
      cost: 65,
    },
    creator: 'system',
    citations: 0,
    validationStatus: 'validated',
  },

  // ── Glass Types ───────────────────────────────────────────────
  {
    id: 'mat-glass-float',
    name: 'Float Glass',
    category: 'glass',
    properties: {
      tensileStrength: 40,
      compressiveStrength: 800,
      shearStrength: 30,
      elasticModulus: 70,
      density: 2500,
      thermalConductivity: 1.0,
      thermalExpansionCoeff: 9e-6,
      meltingPoint: 700,
      fireResistanceHours: 0.25,
      corrosionResistance: 'extreme',
      fatigueLimit: 20,
      cost: 45,
    },
    creator: 'system',
    citations: 0,
    validationStatus: 'validated',
  },
  {
    id: 'mat-glass-tempered',
    name: 'Tempered Safety Glass',
    category: 'glass',
    properties: {
      tensileStrength: 120,
      compressiveStrength: 900,
      shearStrength: 80,
      elasticModulus: 70,
      density: 2500,
      thermalConductivity: 1.0,
      thermalExpansionCoeff: 9e-6,
      meltingPoint: 700,
      fireResistanceHours: 0.5,
      corrosionResistance: 'extreme',
      fatigueLimit: 55,
      cost: 90,
    },
    creator: 'system',
    citations: 0,
    validationStatus: 'validated',
  },
];
