/**
 * Lens Identity System — 112 lenses, 112 identities, one design system.
 *
 * Each lens gets its own visual personality: accent colors, gradients,
 * content layout style, card style, and vibe. The underlying design system
 * is shared — same buttons, same spacing, same font scale. Just different
 * colors and layouts on top.
 *
 * CSS variables are scoped per-lens via useLensIdentity hook:
 *   --lens-accent, --lens-secondary, --lens-gradient
 */

export interface LensIdentity {
  accent: string;
  secondaryAccent: string;
  icon: string;
  gradient: string;
  contentLayout: string;
  cardStyle: string;
  emptyState: string;
  vibe: string;
}

export const LENS_IDENTITIES: Record<string, LensIdentity> = {
  music: {
    accent: "#E84CCA",
    secondaryAccent: "#8B5CF6",
    icon: "\u{1F3B5}",
    gradient: "linear-gradient(135deg, #E84CCA22, #8B5CF622)",
    contentLayout: "player",
    cardStyle: "album",
    emptyState: "No tracks yet. Be the first to drop something.",
    vibe: "spotify-meets-soundcloud",
  },
  news: {
    accent: "#EF5B5B",
    secondaryAccent: "#F0EDE8",
    icon: "\u{1F4F0}",
    gradient: "linear-gradient(135deg, #EF5B5B11, #F0EDE811)",
    contentLayout: "editorial",
    cardStyle: "article",
    emptyState: "Live feeds loading...",
    vibe: "reuters-clean",
  },
  code: {
    accent: "#3ECFA0",
    secondaryAccent: "#1C1C20",
    icon: "\u{1F4BB}",
    gradient: "linear-gradient(135deg, #3ECFA011, #1C1C2022)",
    contentLayout: "ide",
    cardStyle: "repo",
    emptyState: "Empty workspace. Start building.",
    vibe: "vscode-minimal",
  },
  art: {
    accent: "#E8A44C",
    secondaryAccent: "#D4603A",
    icon: "\u{1F3A8}",
    gradient: "linear-gradient(135deg, #E8A44C11, #D4603A11)",
    contentLayout: "gallery",
    cardStyle: "artwork",
    emptyState: "A blank canvas waiting for you.",
    vibe: "gallery-exhibition",
  },
  finance: {
    accent: "#5B8DEF",
    secondaryAccent: "#3ECFA0",
    icon: "\u{1F4CA}",
    gradient: "linear-gradient(135deg, #5B8DEF11, #3ECFA011)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "Markets are loading...",
    vibe: "bloomberg-clean",
  },
  legal: {
    accent: "#9B978F",
    secondaryAccent: "#E8A44C",
    icon: "\u{2696}\u{FE0F}",
    gradient: "linear-gradient(135deg, #9B978F11, #E8A44C11)",
    contentLayout: "document",
    cardStyle: "document",
    emptyState: "No documents yet. Create one to get started.",
    vibe: "law-firm-modern",
  },
  trades: {
    accent: "#E87D3E",
    secondaryAccent: "#8B7355",
    icon: "\u{1F527}",
    gradient: "linear-gradient(135deg, #E87D3E11, #8B735511)",
    contentLayout: "tutorial",
    cardStyle: "project",
    emptyState: "No tutorials yet. Share your craft.",
    vibe: "workshop-practical",
  },
  healthcare: {
    accent: "#4CADE8",
    secondaryAccent: "#FFFFFF",
    icon: "\u{1F3E5}",
    gradient: "linear-gradient(135deg, #4CADE811, #FFFFFF08)",
    contentLayout: "reference",
    cardStyle: "clinical",
    emptyState: "Health resources loading. Not medical advice.",
    vibe: "medical-trusted",
  },
  forum: {
    accent: "#E8A44C",
    secondaryAccent: "#9B978F",
    icon: "\u{1F4AC}",
    gradient: "linear-gradient(135deg, #E8A44C11, #9B978F11)",
    contentLayout: "threads",
    cardStyle: "thread",
    emptyState: "Start a discussion. Ask anything.",
    vibe: "reddit-clean",
  },
  research: {
    accent: "#6ECFA0",
    secondaryAccent: "#5B8DEF",
    icon: "\u{1F52C}",
    gradient: "linear-gradient(135deg, #6ECFA011, #5B8DEF11)",
    contentLayout: "paper",
    cardStyle: "paper",
    emptyState: "No papers yet. Real arXiv feeds loading.",
    vibe: "arxiv-modern",
  },
  studio: {
    accent: "#E84C6A",
    secondaryAccent: "#E8A44C",
    icon: "\u{1F399}\u{FE0F}",
    gradient: "linear-gradient(135deg, #E84C6A11, #E8A44C11)",
    contentLayout: "daw",
    cardStyle: "track",
    emptyState: "Studio is quiet. Record something.",
    vibe: "ableton-minimal",
  },
  education: {
    accent: "#5BC8EF",
    secondaryAccent: "#3ECFA0",
    icon: "\u{1F4DA}",
    gradient: "linear-gradient(135deg, #5BC8EF11, #3ECFA011)",
    contentLayout: "course",
    cardStyle: "lesson",
    emptyState: "Courses loading. What do you want to learn?",
    vibe: "coursera-warm",
  },
  robotics: {
    accent: "#7B8DEF",
    secondaryAccent: "#3ECFA0",
    icon: "\u{1F916}",
    gradient: "linear-gradient(135deg, #7B8DEF11, #3ECFA011)",
    contentLayout: "specs",
    cardStyle: "component",
    emptyState: "No robotics content yet. Build something.",
    vibe: "engineering-dashboard",
  },
  eco: {
    accent: "#4CAE6A",
    secondaryAccent: "#8BC34A",
    icon: "\u{1F30D}",
    gradient: "linear-gradient(135deg, #4CAE6A11, #8BC34A11)",
    contentLayout: "data",
    cardStyle: "species",
    emptyState: "Ecosystem data loading from live feeds.",
    vibe: "national-geographic-data",
  },
  world: {
    accent: "#E8A44C",
    secondaryAccent: "#8B5CF6",
    icon: "\u{1F310}",
    gradient: "linear-gradient(135deg, #E8A44C11, #8B5CF611)",
    contentLayout: "isometric",
    cardStyle: "district",
    emptyState: "Loading world...",
    vibe: "game-world-ui",
  },
  gaming: {
    accent: "#8B5CF6",
    secondaryAccent: "#E84CCA",
    icon: "\u{1F3AE}",
    gradient: "linear-gradient(135deg, #8B5CF622, #E84CCA11)",
    contentLayout: "feed",
    cardStyle: "game",
    emptyState: "No games discussed yet. Start the conversation.",
    vibe: "twitch-meets-steam",
  },
  // ── Additional common lenses ──
  marketplace: {
    accent: "#3ECFA0",
    secondaryAccent: "#E8A44C",
    icon: "\u{1F6D2}",
    gradient: "linear-gradient(135deg, #3ECFA011, #E8A44C11)",
    contentLayout: "feed",
    cardStyle: "listing",
    emptyState: "Marketplace is empty. List something.",
    vibe: "etsy-modern",
  },
  feed: {
    accent: "#5B8DEF",
    secondaryAccent: "#E84CCA",
    icon: "\u{1F4F1}",
    gradient: "linear-gradient(135deg, #5B8DEF11, #E84CCA11)",
    contentLayout: "feed",
    cardStyle: "post",
    emptyState: "Your feed is empty. Follow some creators.",
    vibe: "social-clean",
  },
  wallet: {
    accent: "#3ECFA0",
    secondaryAccent: "#5B8DEF",
    icon: "\u{1F4B0}",
    gradient: "linear-gradient(135deg, #3ECFA011, #5B8DEF11)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No transactions yet.",
    vibe: "fintech-clean",
  },
  photography: {
    accent: "#D4603A",
    secondaryAccent: "#E8A44C",
    icon: "\u{1F4F7}",
    gradient: "linear-gradient(135deg, #D4603A11, #E8A44C11)",
    contentLayout: "gallery",
    cardStyle: "artwork",
    emptyState: "No photos yet. Capture the moment.",
    vibe: "unsplash-clean",
  },
  film: {
    accent: "#E84C6A",
    secondaryAccent: "#E8A44C",
    icon: "\u{1F3AC}",
    gradient: "linear-gradient(135deg, #E84C6A11, #E8A44C11)",
    contentLayout: "gallery",
    cardStyle: "album",
    emptyState: "No films yet. Lights, camera, action.",
    vibe: "imdb-dark",
  },
  podcast: {
    accent: "#8B5CF6",
    secondaryAccent: "#E84CCA",
    icon: "\u{1F3A7}",
    gradient: "linear-gradient(135deg, #8B5CF622, #E84CCA11)",
    contentLayout: "player",
    cardStyle: "album",
    emptyState: "No episodes yet. Start recording.",
    vibe: "spotify-podcasts",
  },
  cooking: {
    accent: "#E87D3E",
    secondaryAccent: "#E8A44C",
    icon: "\u{1F373}",
    gradient: "linear-gradient(135deg, #E87D3E11, #E8A44C11)",
    contentLayout: "tutorial",
    cardStyle: "project",
    emptyState: "No recipes yet. Share your kitchen magic.",
    vibe: "food-network-warm",
  },
  fitness: {
    accent: "#3ECFA0",
    secondaryAccent: "#5B8DEF",
    icon: "\u{1F4AA}",
    gradient: "linear-gradient(135deg, #3ECFA011, #5B8DEF11)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No workouts logged. Let's get moving.",
    vibe: "strava-clean",
  },
  science: {
    accent: "#6ECFA0",
    secondaryAccent: "#5B8DEF",
    icon: "\u{1F9EA}",
    gradient: "linear-gradient(135deg, #6ECFA011, #5B8DEF11)",
    contentLayout: "paper",
    cardStyle: "paper",
    emptyState: "Experiments loading...",
    vibe: "nature-journal",
  },
  math: {
    accent: "#5B8DEF",
    secondaryAccent: "#8B5CF6",
    icon: "\u{1F4D0}",
    gradient: "linear-gradient(135deg, #5B8DEF11, #8B5CF611)",
    contentLayout: "document",
    cardStyle: "document",
    emptyState: "No proofs yet. x\u00B2-x=0.",
    vibe: "academic-clean",
  },
  history: {
    accent: "#9B978F",
    secondaryAccent: "#E8A44C",
    icon: "\u{1F3DB}\u{FE0F}",
    gradient: "linear-gradient(135deg, #9B978F11, #E8A44C11)",
    contentLayout: "editorial",
    cardStyle: "article",
    emptyState: "History loading from the timeline...",
    vibe: "archive-scholarly",
  },
  philosophy: {
    accent: "#8B5CF6",
    secondaryAccent: "#9B978F",
    icon: "\u{1F914}",
    gradient: "linear-gradient(135deg, #8B5CF611, #9B978F11)",
    contentLayout: "threads",
    cardStyle: "thread",
    emptyState: "The unexamined feed is not worth scrolling.",
    vibe: "socratic-minimal",
  },
  sports: {
    accent: "#EF5B5B",
    secondaryAccent: "#3ECFA0",
    icon: "\u{26BD}",
    gradient: "linear-gradient(135deg, #EF5B5B11, #3ECFA011)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "Scores loading...",
    vibe: "espn-live",
  },
  travel: {
    accent: "#4CADE8",
    secondaryAccent: "#E8A44C",
    icon: "\u{2708}\u{FE0F}",
    gradient: "linear-gradient(135deg, #4CADE811, #E8A44C11)",
    contentLayout: "gallery",
    cardStyle: "artwork",
    emptyState: "Where to next?",
    vibe: "lonely-planet",
  },
  security: {
    accent: "#EF5B5B",
    secondaryAccent: "#1C1C20",
    icon: "\u{1F6E1}\u{FE0F}",
    gradient: "linear-gradient(135deg, #EF5B5B11, #1C1C2022)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "All systems nominal.",
    vibe: "security-ops",
  },
  space: {
    accent: "#7B8DEF",
    secondaryAccent: "#1C1C20",
    icon: "\u{1F680}",
    gradient: "linear-gradient(135deg, #7B8DEF22, #1C1C2022)",
    contentLayout: "data",
    cardStyle: "metric",
    emptyState: "Scanning the cosmos...",
    vibe: "nasa-dark",
  },
};

// Fallback for lenses without a defined identity
export const DEFAULT_IDENTITY: LensIdentity = {
  accent: "#5B8DEF",
  secondaryAccent: "#9B978F",
  icon: "\u{1F50D}",
  gradient: "linear-gradient(135deg, #5B8DEF11, #9B978F11)",
  contentLayout: "feed",
  cardStyle: "default",
  emptyState: "No content yet.",
  vibe: "default",
};

/**
 * Get identity for a lens, falling back to DEFAULT_IDENTITY.
 */
export function getLensIdentity(domain: string): LensIdentity {
  return LENS_IDENTITIES[domain] || DEFAULT_IDENTITY;
}
