/**
 * Lens Identity System — 175+ lenses, 175+ identities, one design system.
 *
 * Every lens gets its own visual personality: accent colors, gradients,
 * content layout style, card style, and vibe. The underlying design system
 * is shared — same buttons, same spacing, same font scale. Just different
 * colors and layouts on top.
 *
 * CSS variables are scoped per-lens via useLensIdentity hook:
 *   --lens-accent, --lens-secondary, --lens-gradient
 *
 * ZERO fallbacks. Every lens has a unique identity.
 */

export interface LensIdentity {
  accent: string;
  secondaryAccent: string;
  icon: string;
  gradient: string;
  contentLayout: string;
  cardStyle: string;
  emptyState: string;
  vibe: string;
}

export const LENS_IDENTITIES: Record<string, LensIdentity> = {
  music: {
    accent: "#E84CCA",
    secondaryAccent: "#8B5CF6",
    icon: "\u{1F3B5}",
    gradient: "linear-gradient(135deg, #E84CCA22, #8B5CF622)",
    contentLayout: "player",
    cardStyle: "album",
    emptyState: "No tracks yet. Be the first to drop something.",
    vibe: "spotify-meets-soundcloud",
  },
  news: {
    accent: "#EF5B5B",
    secondaryAccent: "#F0EDE8",
    icon: "\u{1F4F0}",
    gradient: "linear-gradient(135deg, #EF5B5B11, #F0EDE811)",
    contentLayout: "editorial",
    cardStyle: "article",
    emptyState: "Live feeds loading...",
    vibe: "reuters-clean",
  },
  code: {
    accent: "#3ECFA0",
    secondaryAccent: "#1C1C20",
    icon: "\u{1F4BB}",
    gradient: "linear-gradient(135deg, #3ECFA011, #1C1C2022)",
    contentLayout: "ide",
    cardStyle: "repo",
    emptyState: "Empty workspace. Start building.",
    vibe: "vscode-minimal",
  },
  art: {
    accent: "#E8A44C",
    secondaryAccent: "#D4603A",
    icon: "\u{1F3A8}",
    gradient: "linear-gradient(135deg, #E8A44C11, #D4603A11)",
    contentLayout: "gallery",
    cardStyle: "artwork",
    emptyState: "A blank canvas waiting for you.",
    vibe: "gallery-exhibition",
  },
  finance: {
    accent: "#5B8DEF",
    secondaryAccent: "#3ECFA0",
    icon: "\u{1F4CA}",
    gradient: "linear-gradient(135deg, #5B8DEF11, #3ECFA011)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "Markets are loading...",
    vibe: "bloomberg-clean",
  },
  legal: {
    accent: "#9B978F",
    secondaryAccent: "#E8A44C",
    icon: "\u{2696}\u{FE0F}",
    gradient: "linear-gradient(135deg, #9B978F11, #E8A44C11)",
    contentLayout: "document",
    cardStyle: "document",
    emptyState: "No documents yet. Create one to get started.",
    vibe: "law-firm-modern",
  },
  trades: {
    accent: "#E87D3E",
    secondaryAccent: "#8B7355",
    icon: "\u{1F527}",
    gradient: "linear-gradient(135deg, #E87D3E11, #8B735511)",
    contentLayout: "tutorial",
    cardStyle: "project",
    emptyState: "No tutorials yet. Share your craft.",
    vibe: "workshop-practical",
  },
  healthcare: {
    accent: "#4CADE8",
    secondaryAccent: "#FFFFFF",
    icon: "\u{1F3E5}",
    gradient: "linear-gradient(135deg, #4CADE811, #FFFFFF08)",
    contentLayout: "reference",
    cardStyle: "clinical",
    emptyState: "Health resources loading. Not medical advice.",
    vibe: "medical-trusted",
  },
  forum: {
    accent: "#E8A44C",
    secondaryAccent: "#9B978F",
    icon: "\u{1F4AC}",
    gradient: "linear-gradient(135deg, #E8A44C11, #9B978F11)",
    contentLayout: "threads",
    cardStyle: "thread",
    emptyState: "Start a discussion. Ask anything.",
    vibe: "reddit-clean",
  },
  research: {
    accent: "#6ECFA0",
    secondaryAccent: "#5B8DEF",
    icon: "\u{1F52C}",
    gradient: "linear-gradient(135deg, #6ECFA011, #5B8DEF11)",
    contentLayout: "paper",
    cardStyle: "paper",
    emptyState: "No papers yet. Real arXiv feeds loading.",
    vibe: "arxiv-modern",
  },
  studio: {
    accent: "#E84C6A",
    secondaryAccent: "#E8A44C",
    icon: "\u{1F399}\u{FE0F}",
    gradient: "linear-gradient(135deg, #E84C6A11, #E8A44C11)",
    contentLayout: "daw",
    cardStyle: "track",
    emptyState: "Studio is quiet. Record something.",
    vibe: "ableton-minimal",
  },
  education: {
    accent: "#5BC8EF",
    secondaryAccent: "#3ECFA0",
    icon: "\u{1F4DA}",
    gradient: "linear-gradient(135deg, #5BC8EF11, #3ECFA011)",
    contentLayout: "course",
    cardStyle: "lesson",
    emptyState: "Courses loading. What do you want to learn?",
    vibe: "coursera-warm",
  },
  robotics: {
    accent: "#7B8DEF",
    secondaryAccent: "#3ECFA0",
    icon: "\u{1F916}",
    gradient: "linear-gradient(135deg, #7B8DEF11, #3ECFA011)",
    contentLayout: "specs",
    cardStyle: "component",
    emptyState: "No robotics content yet. Build something.",
    vibe: "engineering-dashboard",
  },
  eco: {
    accent: "#4CAE6A",
    secondaryAccent: "#8BC34A",
    icon: "\u{1F30D}",
    gradient: "linear-gradient(135deg, #4CAE6A11, #8BC34A11)",
    contentLayout: "data",
    cardStyle: "species",
    emptyState: "Ecosystem data loading from live feeds.",
    vibe: "national-geographic-data",
  },
  world: {
    accent: "#E8A44C",
    secondaryAccent: "#8B5CF6",
    icon: "\u{1F310}",
    gradient: "linear-gradient(135deg, #E8A44C11, #8B5CF611)",
    contentLayout: "isometric",
    cardStyle: "district",
    emptyState: "Loading world...",
    vibe: "game-world-ui",
  },
  // ── Additional common lenses ──
  marketplace: {
    accent: "#3ECFA0",
    secondaryAccent: "#E8A44C",
    icon: "\u{1F6D2}",
    gradient: "linear-gradient(135deg, #3ECFA011, #E8A44C11)",
    contentLayout: "feed",
    cardStyle: "listing",
    emptyState: "Marketplace is empty. List something.",
    vibe: "etsy-modern",
  },
  feed: {
    accent: "#5B8DEF",
    secondaryAccent: "#E84CCA",
    icon: "\u{1F4F1}",
    gradient: "linear-gradient(135deg, #5B8DEF11, #E84CCA11)",
    contentLayout: "feed",
    cardStyle: "post",
    emptyState: "Your feed is empty. Follow some creators.",
    vibe: "social-clean",
  },
  wallet: {
    accent: "#3ECFA0",
    secondaryAccent: "#5B8DEF",
    icon: "\u{1F4B0}",
    gradient: "linear-gradient(135deg, #3ECFA011, #5B8DEF11)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No transactions yet.",
    vibe: "fintech-clean",
  },
  photography: {
    accent: "#D4603A",
    secondaryAccent: "#E8A44C",
    icon: "\u{1F4F7}",
    gradient: "linear-gradient(135deg, #D4603A11, #E8A44C11)",
    contentLayout: "gallery",
    cardStyle: "artwork",
    emptyState: "No photos yet. Capture the moment.",
    vibe: "unsplash-clean",
  },
  podcast: {
    accent: "#8B5CF6",
    secondaryAccent: "#E84CCA",
    icon: "\u{1F3A7}",
    gradient: "linear-gradient(135deg, #8B5CF622, #E84CCA11)",
    contentLayout: "player",
    cardStyle: "album",
    emptyState: "No episodes yet. Start recording.",
    vibe: "spotify-podcasts",
  },
  cooking: {
    accent: "#E87D3E",
    secondaryAccent: "#E8A44C",
    icon: "\u{1F373}",
    gradient: "linear-gradient(135deg, #E87D3E11, #E8A44C11)",
    contentLayout: "tutorial",
    cardStyle: "project",
    emptyState: "No recipes yet. Share your kitchen magic.",
    vibe: "food-network-warm",
  },
  fitness: {
    accent: "#3ECFA0",
    secondaryAccent: "#5B8DEF",
    icon: "\u{1F4AA}",
    gradient: "linear-gradient(135deg, #3ECFA011, #5B8DEF11)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No workouts logged. Let's get moving.",
    vibe: "strava-clean",
  },
  science: {
    accent: "#6ECFA0",
    secondaryAccent: "#5B8DEF",
    icon: "\u{1F9EA}",
    gradient: "linear-gradient(135deg, #6ECFA011, #5B8DEF11)",
    contentLayout: "paper",
    cardStyle: "paper",
    emptyState: "Experiments loading...",
    vibe: "nature-journal",
  },
  math: {
    accent: "#5B8DEF",
    secondaryAccent: "#8B5CF6",
    icon: "\u{1F4D0}",
    gradient: "linear-gradient(135deg, #5B8DEF11, #8B5CF611)",
    contentLayout: "document",
    cardStyle: "document",
    emptyState: "No proofs yet. x\u00B2-x=0.",
    vibe: "academic-clean",
  },
  history: {
    accent: "#9B978F",
    secondaryAccent: "#E8A44C",
    icon: "\u{1F3DB}\u{FE0F}",
    gradient: "linear-gradient(135deg, #9B978F11, #E8A44C11)",
    contentLayout: "editorial",
    cardStyle: "article",
    emptyState: "History loading from the timeline...",
    vibe: "archive-scholarly",
  },
  philosophy: {
    accent: "#8B5CF6",
    secondaryAccent: "#9B978F",
    icon: "\u{1F914}",
    gradient: "linear-gradient(135deg, #8B5CF611, #9B978F11)",
    contentLayout: "threads",
    cardStyle: "thread",
    emptyState: "The unexamined feed is not worth scrolling.",
    vibe: "socratic-minimal",
  },
  sports: {
    accent: "#EF5B5B",
    secondaryAccent: "#3ECFA0",
    icon: "\u{26BD}",
    gradient: "linear-gradient(135deg, #EF5B5B11, #3ECFA011)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "Scores loading...",
    vibe: "espn-live",
  },
  travel: {
    accent: "#4CADE8",
    secondaryAccent: "#E8A44C",
    icon: "\u{2708}\u{FE0F}",
    gradient: "linear-gradient(135deg, #4CADE811, #E8A44C11)",
    contentLayout: "gallery",
    cardStyle: "artwork",
    emptyState: "Where to next?",
    vibe: "lonely-planet",
  },
  security: {
    accent: "#EF5B5B",
    secondaryAccent: "#1C1C20",
    icon: "\u{1F6E1}\u{FE0F}",
    gradient: "linear-gradient(135deg, #EF5B5B11, #1C1C2022)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "All systems nominal.",
    vibe: "security-ops",
  },
  space: {
    accent: "#7B8DEF",
    secondaryAccent: "#1C1C20",
    icon: "\u{1F680}",
    gradient: "linear-gradient(135deg, #7B8DEF22, #1C1C2022)",
    contentLayout: "data",
    cardStyle: "metric",
    emptyState: "Scanning the cosmos...",
    vibe: "nasa-dark",
  },
  agents: {
    accent: "#7C4DFF",
    secondaryAccent: "#6200EA",
    icon: "\u{1F916}",
    gradient: "linear-gradient(135deg, #7C4DFF11, #6200EA11)",
    contentLayout: "dashboard",
    cardStyle: "component",
    emptyState: "No autonomous agents deployed. Create your first agent.",
    vibe: "vercel-minimal",
  },
  analytics: {
    accent: "#00ACC1",
    secondaryAccent: "#00838F",
    icon: "\u{1F4CA}",
    gradient: "linear-gradient(135deg, #00ACC111, #00838F11)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No data streams connected. Wire up your first metric.",
    vibe: "mixpanel-clean",
  },
  animation: {
    accent: "#F06292",
    secondaryAccent: "#EC407A",
    icon: "\u{1F3AC}",
    gradient: "linear-gradient(135deg, #F0629211, #EC407A11)",
    contentLayout: "gallery",
    cardStyle: "artwork",
    emptyState: "No keyframes created. Start your first animation.",
    vibe: "after-effects-dark",
  },
  astronomy: {
    accent: "#1A237E",
    secondaryAccent: "#0D1B4A",
    icon: "\u{1F52D}",
    gradient: "linear-gradient(135deg, #1A237E22, #0D1B4A22)",
    contentLayout: "reference",
    cardStyle: "paper",
    emptyState: "No celestial observations logged. Point your telescope.",
    vibe: "nasa-deep-space",
  },
  bridge: {
    accent: "#5C6BC0",
    secondaryAccent: "#3949AB",
    icon: "\u{1F309}",
    gradient: "linear-gradient(135deg, #5C6BC011, #3949AB11)",
    contentLayout: "data",
    cardStyle: "component",
    emptyState: "No bridges or integrations configured. Connect your first system.",
    vibe: "zapier-connect",
  },
  calendar: {
    accent: "#039BE5",
    secondaryAccent: "#0277BD",
    icon: "\u{1F4C5}",
    gradient: "linear-gradient(135deg, #039BE511, #0277BD11)",
    contentLayout: "dashboard",
    cardStyle: "default",
    emptyState: "No events scheduled. Create your first event.",
    vibe: "google-calendar",
  },
  carpentry: {
    accent: "#8D6E63",
    secondaryAccent: "#6D4C41",
    icon: "\u{1FA9A}",
    gradient: "linear-gradient(135deg, #8D6E6311, #6D4C4111)",
    contentLayout: "tutorial",
    cardStyle: "project",
    emptyState: "No woodworking plans drafted. Start your first project.",
    vibe: "workshop-grain",
  },
  collab: {
    accent: "#42A5F5",
    secondaryAccent: "#1E88E5",
    icon: "\u{1F46B}",
    gradient: "linear-gradient(135deg, #42A5F511, #1E88E511)",
    contentLayout: "threads",
    cardStyle: "thread",
    emptyState: "No collaboration sessions active. Start working together.",
    vibe: "figma-collab",
  },
  daily: {
    accent: "#FFA726",
    secondaryAccent: "#FB8C00",
    icon: "\u{2600}",
    gradient: "linear-gradient(135deg, #FFA72611, #FB8C0011)",
    contentLayout: "feed",
    cardStyle: "post",
    emptyState: "Your daily briefing is empty. Log your first entry.",
    vibe: "morning-brew-warm",
  },
  database: {
    accent: "#00695C",
    secondaryAccent: "#004D40",
    icon: "\u{1F5C4}",
    gradient: "linear-gradient(135deg, #00695C11, #004D4011)",
    contentLayout: "data",
    cardStyle: "repo",
    emptyState: "No schemas or queries stored. Create your first table.",
    vibe: "datagrip-dark",
  },
  debate: {
    accent: "#C2185B",
    secondaryAccent: "#880E4F",
    icon: "\u{1F5E3}",
    gradient: "linear-gradient(135deg, #C2185B11, #880E4F11)",
    contentLayout: "threads",
    cardStyle: "thread",
    emptyState: "No arguments on the floor. Open a debate.",
    vibe: "oxford-union",
  },
  defense: {
    accent: "#263238",
    secondaryAccent: "#1B262C",
    icon: "\u{1F6E1}",
    gradient: "linear-gradient(135deg, #26323822, #1B262C22)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No threat assessments active. All clear.",
    vibe: "palantir-dark",
  },
  disputes: {
    accent: "#D84315",
    secondaryAccent: "#BF360C",
    icon: "\u{2696}",
    gradient: "linear-gradient(135deg, #D8431511, #BF360C11)",
    contentLayout: "threads",
    cardStyle: "document",
    emptyState: "No disputes filed. All parties in agreement.",
    vibe: "westlaw-formal",
  },
  electrical: {
    accent: "#FDD835",
    secondaryAccent: "#F9A825",
    icon: "\u{26A1}",
    gradient: "linear-gradient(135deg, #FDD83511, #F9A82511)",
    contentLayout: "specs",
    cardStyle: "component",
    emptyState: "No circuits or wiring schematics loaded.",
    vibe: "autodesk-electrical",
  },
  "emergency-services": {
    accent: "#D50000",
    secondaryAccent: "#B71C1C",
    icon: "\u{1F6A8}",
    gradient: "linear-gradient(135deg, #D5000011, #B71C1C11)",
    contentLayout: "dashboard",
    cardStyle: "clinical",
    emptyState: "No active emergencies. All units standing by.",
    vibe: "911-dispatch",
  },
  energy: {
    accent: "#FFB300",
    secondaryAccent: "#FF8F00",
    icon: "\u{1F50B}",
    gradient: "linear-gradient(135deg, #FFB30011, #FF8F0011)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No energy data streams connected.",
    vibe: "siemens-grid",
  },
  experience: {
    accent: "#EC407A",
    secondaryAccent: "#D81B60",
    icon: "\u{1F3AF}",
    gradient: "linear-gradient(135deg, #EC407A11, #D81B6011)",
    contentLayout: "gallery",
    cardStyle: "artwork",
    emptyState: "No user journeys mapped. Start designing the experience.",
    vibe: "invision-ux",
  },
  "export": {
    accent: "#1E88E5",
    secondaryAccent: "#1565C0",
    icon: "\u{1F4E4}",
    gradient: "linear-gradient(135deg, #1E88E511, #1565C011)",
    contentLayout: "data",
    cardStyle: "default",
    emptyState: "No export jobs queued. Package your data.",
    vibe: "aws-s3-clean",
  },
  fashion: {
    accent: "#F48FB1",
    secondaryAccent: "#F06292",
    icon: "\u{1F457}",
    gradient: "linear-gradient(135deg, #F48FB111, #F0629211)",
    contentLayout: "gallery",
    cardStyle: "artwork",
    emptyState: "No collections curated. Build your lookbook.",
    vibe: "vogue-editorial",
  },
  "film-studios": {
    accent: "#880E4F",
    secondaryAccent: "#6A0036",
    icon: "\u{1F3AC}",
    gradient: "linear-gradient(135deg, #880E4F22, #6A003622)",
    contentLayout: "gallery",
    cardStyle: "artwork",
    emptyState: "No productions in development. Lights, camera, action.",
    vibe: "imdb-cinematic",
  },
  engineering: {
    accent: "#37474F",
    secondaryAccent: "#263238",
    icon: "\u{1F527}",
    gradient: "linear-gradient(135deg, #37474F11, #26323811)",
    contentLayout: "specs",
    cardStyle: "component",
    emptyState: "No engineering specs or drawings filed.",
    vibe: "solidworks-precision",
  },
  desert: {
    accent: "#D4A056",
    secondaryAccent: "#BF8C3E",
    icon: "\u{1F3DC}",
    gradient: "linear-gradient(135deg, #D4A05611, #BF8C3E11)",
    contentLayout: "gallery",
    cardStyle: "district",
    emptyState: "No arid terrain data. Start surveying.",
    vibe: "natgeo-warm",
  },
  consulting: {
    accent: "#455A64",
    secondaryAccent: "#37474F",
    icon: "\u{1F4BC}",
    gradient: "linear-gradient(135deg, #455A6411, #37474F11)",
    contentLayout: "document",
    cardStyle: "document",
    emptyState: "No client engagements tracked. Start your first project.",
    vibe: "mckinsey-formal",
  },
  council: {
    accent: "#3F51B5",
    secondaryAccent: "#303F9F",
    icon: "\u{1F3DB}",
    gradient: "linear-gradient(135deg, #3F51B511, #303F9F11)",
    contentLayout: "threads",
    cardStyle: "thread",
    emptyState: "No council motions on record. Submit a proposal.",
    vibe: "parliament-blue",
  },
  "creative-writing": {
    accent: "#8E24AA",
    secondaryAccent: "#6A1B9A",
    icon: "\u{1F58B}",
    gradient: "linear-gradient(135deg, #8E24AA11, #6A1B9A11)",
    contentLayout: "editorial",
    cardStyle: "article",
    emptyState: "No manuscripts in the workshop. Write your first draft.",
    vibe: "medium-editorial",
  },
  custom: {
    accent: "#9E9E9E",
    secondaryAccent: "#757575",
    icon: "\u{2699}",
    gradient: "linear-gradient(135deg, #9E9E9E11, #75757511)",
    contentLayout: "feed",
    cardStyle: "default",
    emptyState: "Custom lens ready. Configure your own schema.",
    vibe: "material-neutral",
  },
  construction: {
    accent: "#F57F17",
    secondaryAccent: "#E65100",
    icon: "\u{1F3D7}",
    gradient: "linear-gradient(135deg, #F57F1711, #E6510011)",
    contentLayout: "dashboard",
    cardStyle: "project",
    emptyState: "No construction projects underway. Break ground.",
    vibe: "procore-build",
  },
  automotive: {
    accent: "#D32F2F",
    secondaryAccent: "#B71C1C",
    icon: "\u{1F697}",
    gradient: "linear-gradient(135deg, #D32F2F11, #B71C1C11)",
    contentLayout: "specs",
    cardStyle: "listing",
    emptyState: "No vehicles tracked. Add your first car.",
    vibe: "tesla-dash",
  },
  materials: {
    accent: "#78909C",
    secondaryAccent: "#607D8B",
    icon: "\u{1F9F2}",
    gradient: "linear-gradient(135deg, #78909C11, #607D8B11)",
    contentLayout: "reference",
    cardStyle: "species",
    emptyState: "No material data sheets loaded. Add your first alloy.",
    vibe: "matweb-reference",
  },
  diy: {
    accent: "#E65100",
    secondaryAccent: "#BF360C",
    icon: "\u{1F6E0}",
    gradient: "linear-gradient(135deg, #E6510011, #BF360C11)",
    contentLayout: "tutorial",
    cardStyle: "project",
    emptyState: "No DIY projects started. Grab your tools and build something.",
    vibe: "instructables-maker",
  },
  questmarket: {
    accent: "#FFD740",
    secondaryAccent: "#FFC400",
    icon: "\u{1F3C6}",
    gradient: "linear-gradient(135deg, #FFD74011, #FFC40011)",
    contentLayout: "feed",
    cardStyle: "game",
    emptyState: "No quests posted. Create a bounty to get started.",
    vibe: "gamified-marketplace",
  },
  parenting: {
    accent: "#FF8A65",
    secondaryAccent: "#FF7043",
    icon: "\u{1F476}",
    gradient: "linear-gradient(135deg, #FF8A6511, #FF704311)",
    contentLayout: "feed",
    cardStyle: "article",
    emptyState: "No milestones logged. Record your child's first steps.",
    vibe: "babycenter-warm",
  },
  pets: {
    accent: "#FFAB40",
    secondaryAccent: "#FF9100",
    icon: "\u{1F43E}",
    gradient: "linear-gradient(135deg, #FFAB4011, #FF910011)",
    contentLayout: "feed",
    cardStyle: "listing",
    emptyState: "No pet profiles registered. Add your first furry friend.",
    vibe: "chewy-friendly",
  },
  // ── Batch 1: 28 additional lenses ──
  accounting: {
    accent: "#2E7D32",
    secondaryAccent: "#1B5E20",
    icon: "📒",
    gradient: "linear-gradient(135deg, #2E7D3211, #1B5E2011)",
    contentLayout: "data",
    cardStyle: "metric",
    emptyState: "No ledger entries recorded. Start tracking your accounts.",
    vibe: "quickbooks-ledger",
  },
  admin: {
    accent: "#546E7A",
    secondaryAccent: "#455A64",
    icon: "⚙️",
    gradient: "linear-gradient(135deg, #546E7A11, #455A6411)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No admin tasks pending. System running smoothly.",
    vibe: "admin-console-clean",
  },
  affect: {
    accent: "#FF80AB",
    secondaryAccent: "#F50057",
    icon: "💗",
    gradient: "linear-gradient(135deg, #FF80AB11, #F5005711)",
    contentLayout: "feed",
    cardStyle: "post",
    emptyState: "No emotional check-ins logged. How are you feeling?",
    vibe: "emotion-tracker",
  },
  agriculture: {
    accent: "#558B2F",
    secondaryAccent: "#33691E",
    icon: "🌾",
    gradient: "linear-gradient(135deg, #558B2F11, #33691E11)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No crop data tracked. Plant your first field entry.",
    vibe: "farm-dashboard",
  },
  alliance: {
    accent: "#7986CB",
    secondaryAccent: "#5C6BC0",
    icon: "🤝",
    gradient: "linear-gradient(135deg, #7986CB11, #5C6BC011)",
    contentLayout: "threads",
    cardStyle: "thread",
    emptyState: "No partnership threads started. Forge your first alliance.",
    vibe: "slack-partnerships",
  },
  anon: {
    accent: "#616161",
    secondaryAccent: "#424242",
    icon: "🎭",
    gradient: "linear-gradient(135deg, #61616111, #42424211)",
    contentLayout: "feed",
    cardStyle: "post",
    emptyState: "No anonymous posts yet. Share something in the shadows.",
    vibe: "tor-minimal",
  },
  "app-maker": {
    accent: "#B388FF",
    secondaryAccent: "#7C4DFF",
    icon: "📱",
    gradient: "linear-gradient(135deg, #B388FF11, #7C4DFF11)",
    contentLayout: "ide",
    cardStyle: "component",
    emptyState: "No apps in progress. Start building your first prototype.",
    vibe: "flutter-builder",
  },
  ar: {
    accent: "#00B8D4",
    secondaryAccent: "#0097A7",
    icon: "🔮",
    gradient: "linear-gradient(135deg, #00B8D411, #0097A711)",
    contentLayout: "isometric",
    cardStyle: "project",
    emptyState: "No AR scenes created. Place your first virtual object.",
    vibe: "arkit-spatial",
  },
  artistry: {
    accent: "#FF6F00",
    secondaryAccent: "#E65100",
    icon: "🖌️",
    gradient: "linear-gradient(135deg, #FF6F0011, #E6510011)",
    contentLayout: "gallery",
    cardStyle: "artwork",
    emptyState: "No artisan works showcased. Upload your first masterpiece.",
    vibe: "behance-portfolio",
  },
  atlas: {
    accent: "#0277BD",
    secondaryAccent: "#01579B",
    icon: "🗺️",
    gradient: "linear-gradient(135deg, #0277BD11, #01579B11)",
    contentLayout: "dashboard",
    cardStyle: "district",
    emptyState: "No regions mapped. Drop your first pin on the atlas.",
    vibe: "mapbox-explorer",
  },
  attention: {
    accent: "#F9A825",
    secondaryAccent: "#F57F17",
    icon: "🎯",
    gradient: "linear-gradient(135deg, #F9A82511, #F57F1711)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No focus sessions recorded. Start your first deep work block.",
    vibe: "focus-tracker",
  },
  audit: {
    accent: "#4A6572",
    secondaryAccent: "#344955",
    icon: "🔍",
    gradient: "linear-gradient(135deg, #4A657211, #34495511)",
    contentLayout: "data",
    cardStyle: "document",
    emptyState: "No audit trails recorded. Begin your compliance review.",
    vibe: "deloitte-compliance",
  },
  aviation: {
    accent: "#1565C0",
    secondaryAccent: "#0D47A1",
    icon: "✈️",
    gradient: "linear-gradient(135deg, #1565C011, #0D47A111)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No flight operations tracked. File your first flight plan.",
    vibe: "flightaware-ops",
  },
  billing: {
    accent: "#43A047",
    secondaryAccent: "#2E7D32",
    icon: "💳",
    gradient: "linear-gradient(135deg, #43A04711, #2E7D3211)",
    contentLayout: "data",
    cardStyle: "metric",
    emptyState: "No invoices generated. Create your first billing cycle.",
    vibe: "stripe-dashboard",
  },
  bio: {
    accent: "#26A69A",
    secondaryAccent: "#00897B",
    icon: "🧬",
    gradient: "linear-gradient(135deg, #26A69A11, #00897B11)",
    contentLayout: "paper",
    cardStyle: "paper",
    emptyState: "No biological datasets loaded. Import your first genome.",
    vibe: "ncbi-research",
  },
  board: {
    accent: "#5D4037",
    secondaryAccent: "#4E342E",
    icon: "📋",
    gradient: "linear-gradient(135deg, #5D403711, #4E342E11)",
    contentLayout: "threads",
    cardStyle: "thread",
    emptyState: "No board items created. Add your first agenda topic.",
    vibe: "notion-board",
  },
  chat: {
    accent: "#7E57C2",
    secondaryAccent: "#673AB7",
    icon: "💬",
    gradient: "linear-gradient(135deg, #7E57C211, #673AB711)",
    contentLayout: "threads",
    cardStyle: "thread",
    emptyState: "No conversations started. Say hello to someone.",
    vibe: "discord-clean",
  },
  chem: {
    accent: "#EF6C00",
    secondaryAccent: "#E65100",
    icon: "⚗️",
    gradient: "linear-gradient(135deg, #EF6C0011, #E6510011)",
    contentLayout: "paper",
    cardStyle: "paper",
    emptyState: "No compounds or reactions logged. Start your first experiment.",
    vibe: "pubchem-lab",
  },
  "command-center": {
    accent: "#283593",
    secondaryAccent: "#1A237E",
    icon: "🖥️",
    gradient: "linear-gradient(135deg, #28359311, #1A237E11)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "All systems offline. Power up your command center.",
    vibe: "mission-control",
  },
  commonsense: {
    accent: "#A1887F",
    secondaryAccent: "#8D6E63",
    icon: "🧠",
    gradient: "linear-gradient(135deg, #A1887F11, #8D6E6311)",
    contentLayout: "feed",
    cardStyle: "post",
    emptyState: "No knowledge entries curated. Share practical wisdom.",
    vibe: "wikipedia-knowledge",
  },
  creative: {
    accent: "#E040FB",
    secondaryAccent: "#D500F9",
    icon: "✨",
    gradient: "linear-gradient(135deg, #E040FB11, #D500F911)",
    contentLayout: "gallery",
    cardStyle: "artwork",
    emptyState: "No creative works uploaded. Let your imagination run wild.",
    vibe: "adobe-creative",
  },
  cri: {
    accent: "#B71C1C",
    secondaryAccent: "#880E4F",
    icon: "🚨",
    gradient: "linear-gradient(135deg, #B71C1C11, #880E4F11)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No critical incidents reported. All systems stable.",
    vibe: "incident-response",
  },
  crypto: {
    accent: "#FF8F00",
    secondaryAccent: "#FF6F00",
    icon: "₿",
    gradient: "linear-gradient(135deg, #FF8F0011, #FF6F0011)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No wallets connected. Link your first crypto address.",
    vibe: "coinbase-trading",
  },
  debug: {
    accent: "#F44336",
    secondaryAccent: "#D32F2F",
    icon: "🐛",
    gradient: "linear-gradient(135deg, #F4433611, #D32F2F11)",
    contentLayout: "ide",
    cardStyle: "repo",
    emptyState: "No bugs to squash. Attach a debugger to get started.",
    vibe: "chrome-devtools",
  },
  docs: {
    accent: "#1976D2",
    secondaryAccent: "#1565C0",
    icon: "📄",
    gradient: "linear-gradient(135deg, #1976D211, #1565C011)",
    contentLayout: "document",
    cardStyle: "document",
    emptyState: "No documents created. Start writing your first page.",
    vibe: "google-docs",
  },
  dtus: {
    accent: "#90A4AE",
    secondaryAccent: "#78909C",
    icon: "🔧",
    gradient: "linear-gradient(135deg, #90A4AE11, #78909C11)",
    contentLayout: "data",
    cardStyle: "component",
    emptyState: "No utilities configured. Add your first dev tool.",
    vibe: "dev-utilities",
  },
  entity: {
    accent: "#00897B",
    secondaryAccent: "#00695C",
    icon: "🏷️",
    gradient: "linear-gradient(135deg, #00897B11, #00695C11)",
    contentLayout: "data",
    cardStyle: "listing",
    emptyState: "No entities defined. Create your first node in the graph.",
    vibe: "entity-graph",
  },
  environment: {
    accent: "#388E3C",
    secondaryAccent: "#2E7D32",
    icon: "🌍",
    gradient: "linear-gradient(135deg, #388E3C11, #2E7D3211)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No environmental sensors connected. Monitor your first biome.",
    vibe: "climate-dashboard",
  },
  "law-enforcement": {
    accent: "#1A237E",
    secondaryAccent: "#283593",
    icon: "🚔",
    gradient: "linear-gradient(135deg, #1A237E11, #28359311)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No incidents logged. Monitor your jurisdiction.",
    vibe: "police-dispatch",
  },
  legacy: {
    accent: "#4E342E",
    secondaryAccent: "#6D4C41",
    icon: "📦",
    gradient: "linear-gradient(135deg, #4E342E11, #6D4C4111)",
    contentLayout: "data",
    cardStyle: "component",
    emptyState: "No legacy systems cataloged. Document your tech debt.",
    vibe: "legacy-archive",
  },
  linguistics: {
    accent: "#7B1FA2",
    secondaryAccent: "#9C27B0",
    icon: "🗣️",
    gradient: "linear-gradient(135deg, #7B1FA211, #9C27B011)",
    contentLayout: "reference",
    cardStyle: "paper",
    emptyState: "No linguistic data. Start your language analysis.",
    vibe: "linguistic-atlas",
  },
  lock: {
    accent: "#37474F",
    secondaryAccent: "#455A64",
    icon: "🔐",
    gradient: "linear-gradient(135deg, #37474F11, #455A6411)",
    contentLayout: "specs",
    cardStyle: "document",
    emptyState: "No locks configured. Define access controls.",
    vibe: "vault-security",
  },
  logistics: {
    accent: "#E64A19",
    secondaryAccent: "#F4511E",
    icon: "🚛",
    gradient: "linear-gradient(135deg, #E64A1911, #F4511E11)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No shipments tracked. Add your first logistics entry.",
    vibe: "fedex-tracking",
  },
  manufacturing: {
    accent: "#BF360C",
    secondaryAccent: "#D84315",
    icon: "🏭",
    gradient: "linear-gradient(135deg, #BF360C11, #D8431511)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No production lines configured. Set up manufacturing.",
    vibe: "siemens-factory",
  },
  market: {
    accent: "#1B5E20",
    secondaryAccent: "#2E7D32",
    icon: "📈",
    gradient: "linear-gradient(135deg, #1B5E2011, #2E7D3211)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No market data loaded. Connect your feeds.",
    vibe: "tradingview-charts",
  },
  marketing: {
    accent: "#C2185B",
    secondaryAccent: "#D81B60",
    icon: "📣",
    gradient: "linear-gradient(135deg, #C2185B11, #D81B6011)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No campaigns running. Launch your first marketing push.",
    vibe: "hubspot-campaigns",
  },
  masonry: {
    accent: "#6D4C41",
    secondaryAccent: "#795548",
    icon: "🧱",
    gradient: "linear-gradient(135deg, #6D4C4111, #79554811)",
    contentLayout: "tutorial",
    cardStyle: "project",
    emptyState: "No masonry projects. Plan your first build.",
    vibe: "masonry-fieldguide",
  },
  "mental-health": {
    accent: "#7986CB",
    secondaryAccent: "#9FA8DA",
    icon: "🧘",
    gradient: "linear-gradient(135deg, #7986CB11, #9FA8DA11)",
    contentLayout: "feed",
    cardStyle: "clinical",
    emptyState: "No wellness logs. Begin your mental health journey.",
    vibe: "calm-wellness",
  },
  mentorship: {
    accent: "#00796B",
    secondaryAccent: "#00897B",
    icon: "🎓",
    gradient: "linear-gradient(135deg, #00796B11, #00897B11)",
    contentLayout: "threads",
    cardStyle: "thread",
    emptyState: "No mentorship sessions. Find or become a mentor.",
    vibe: "mentorship-platform",
  },
  meta: {
    accent: "#5E35B1",
    secondaryAccent: "#7E57C2",
    icon: "🔄",
    gradient: "linear-gradient(135deg, #5E35B111, #7E57C211)",
    contentLayout: "specs",
    cardStyle: "component",
    emptyState: "No meta-configurations. Define system metadata.",
    vibe: "meta-layer",
  },
  metacognition: {
    accent: "#4A148C",
    secondaryAccent: "#6A1B9A",
    icon: "🪞",
    gradient: "linear-gradient(135deg, #4A148C11, #6A1B9A11)",
    contentLayout: "paper",
    cardStyle: "paper",
    emptyState: "No metacognitive reflections. Think about your thinking.",
    vibe: "metacog-journal",
  },
  metalearning: {
    accent: "#6A1B9A",
    secondaryAccent: "#7B1FA2",
    icon: "📚",
    gradient: "linear-gradient(135deg, #6A1B9A11, #7B1FA211)",
    contentLayout: "course",
    cardStyle: "lesson",
    emptyState: "No learning strategies mapped. Optimize how you learn.",
    vibe: "learning-optimizer",
  },
  mining: {
    accent: "#3E2723",
    secondaryAccent: "#4E342E",
    icon: "⛏️",
    gradient: "linear-gradient(135deg, #3E272311, #4E342E11)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No mining operations tracked. Add extraction data.",
    vibe: "mining-ops",
  },
  ml: {
    accent: "#0091EA",
    secondaryAccent: "#00B0FF",
    icon: "🤖",
    gradient: "linear-gradient(135deg, #0091EA11, #00B0FF11)",
    contentLayout: "ide",
    cardStyle: "repo",
    emptyState: "No ML models. Train your first model.",
    vibe: "tensorflow-playground",
  },
  neuro: {
    accent: "#CE93D8",
    secondaryAccent: "#E1BEE7",
    icon: "🧠",
    gradient: "linear-gradient(135deg, #CE93D811, #E1BEE711)",
    contentLayout: "paper",
    cardStyle: "paper",
    emptyState: "No neuroscience data. Begin brain exploration.",
    vibe: "neuro-imaging",
  },
  nonprofit: {
    accent: "#2E7D32",
    secondaryAccent: "#43A047",
    icon: "💚",
    gradient: "linear-gradient(135deg, #2E7D3211, #43A04711)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No nonprofit programs tracked. Start making impact.",
    vibe: "charity-navigator",
  },
  ocean: {
    accent: "#01579B",
    secondaryAccent: "#0277BD",
    icon: "🌊",
    gradient: "linear-gradient(135deg, #01579B11, #0277BD11)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No ocean data recorded. Dive into marine science.",
    vibe: "noaa-ocean",
  },
  offline: {
    accent: "#757575",
    secondaryAccent: "#9E9E9E",
    icon: "📴",
    gradient: "linear-gradient(135deg, #75757511, #9E9E9E11)",
    contentLayout: "data",
    cardStyle: "component",
    emptyState: "No offline data cached. Configure sync settings.",
    vibe: "offline-first",
  },
  organ: {
    accent: "#C62828",
    secondaryAccent: "#D32F2F",
    icon: "🫀",
    gradient: "linear-gradient(135deg, #C6282811, #D32F2F11)",
    contentLayout: "data",
    cardStyle: "clinical",
    emptyState: "No organ data tracked. Add physiological records.",
    vibe: "organ-registry",
  },
  paper: {
    accent: "#4E342E",
    secondaryAccent: "#5D4037",
    icon: "📝",
    gradient: "linear-gradient(135deg, #4E342E11, #5D403711)",
    contentLayout: "paper",
    cardStyle: "paper",
    emptyState: "No papers drafted. Start your manuscript.",
    vibe: "overleaf-editor",
  },
  pharmacy: {
    accent: "#1565C0",
    secondaryAccent: "#1976D2",
    icon: "💊",
    gradient: "linear-gradient(135deg, #1565C011, #1976D211)",
    contentLayout: "data",
    cardStyle: "clinical",
    emptyState: "No prescriptions tracked. Add medication records.",
    vibe: "pharmacy-dispense",
  },
  physics: {
    accent: "#1A237E",
    secondaryAccent: "#283593",
    icon: "⚛️",
    gradient: "linear-gradient(135deg, #1A237E11, #28359311)",
    contentLayout: "paper",
    cardStyle: "paper",
    emptyState: "No physics experiments logged. Explore the fundamental.",
    vibe: "cern-research",
  },
  platform: {
    accent: "#212121",
    secondaryAccent: "#424242",
    icon: "🏗️",
    gradient: "linear-gradient(135deg, #21212111, #42424211)",
    contentLayout: "specs",
    cardStyle: "component",
    emptyState: "No platform services configured. Build your infrastructure.",
    vibe: "aws-console",
  },
  plumbing: {
    accent: "#0277BD",
    secondaryAccent: "#0288D1",
    icon: "🔧",
    gradient: "linear-gradient(135deg, #0277BD11, #0288D111)",
    contentLayout: "tutorial",
    cardStyle: "project",
    emptyState: "No plumbing jobs tracked. Log your first service call.",
    vibe: "plumbing-pro",
  },
  poetry: {
    accent: "#8E24AA",
    secondaryAccent: "#AB47BC",
    icon: "✍️",
    gradient: "linear-gradient(135deg, #8E24AA11, #AB47BC11)",
    contentLayout: "editorial",
    cardStyle: "article",
    emptyState: "No poems composed. Let the words flow.",
    vibe: "poetry-foundation",
  },
  privacy: {
    accent: "#263238",
    secondaryAccent: "#37474F",
    icon: "🔏",
    gradient: "linear-gradient(135deg, #26323811, #37474F11)",
    contentLayout: "document",
    cardStyle: "document",
    emptyState: "No privacy policies defined. Protect user data.",
    vibe: "gdpr-compliance",
  },
  // ── Batch 2: 28 additional lenses ──
  ethics: {
    accent: "#6A1B9A",
    secondaryAccent: "#CE93D8",
    icon: "⚖️",
    gradient: "linear-gradient(135deg, #6A1B9A11, #CE93D811)",
    contentLayout: "document",
    cardStyle: "paper",
    emptyState: "No ethical frameworks defined. Start a moral inquiry.",
    vibe: "philosophy-journal",
  },
  events: {
    accent: "#AD1457",
    secondaryAccent: "#F48FB1",
    icon: "🎪",
    gradient: "linear-gradient(135deg, #AD145711, #F48FB111)",
    contentLayout: "feed",
    cardStyle: "listing",
    emptyState: "No events scheduled. Plan something memorable.",
    vibe: "eventbrite-planner",
  },
  food: {
    accent: "#E65100",
    secondaryAccent: "#FFB74D",
    icon: "🍽️",
    gradient: "linear-gradient(135deg, #E6510011, #FFB74D11)",
    contentLayout: "feed",
    cardStyle: "listing",
    emptyState: "No recipes or food logs. Start your culinary journey.",
    vibe: "yelp-foodie",
  },
  forestry: {
    accent: "#1B5E20",
    secondaryAccent: "#81C784",
    icon: "🌲",
    gradient: "linear-gradient(135deg, #1B5E2011, #81C78411)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No forestry data. Add timber or conservation records.",
    vibe: "forest-service",
  },
  fork: {
    accent: "#546E7A",
    secondaryAccent: "#B0BEC5",
    icon: "🍴",
    gradient: "linear-gradient(135deg, #546E7A11, #B0BEC511)",
    contentLayout: "data",
    cardStyle: "component",
    emptyState: "No forks tracked. Branch off something interesting.",
    vibe: "github-forks",
  },
  fractal: {
    accent: "#AA00FF",
    secondaryAccent: "#EA80FC",
    icon: "🔀",
    gradient: "linear-gradient(135deg, #AA00FF11, #EA80FC11)",
    contentLayout: "isometric",
    cardStyle: "project",
    emptyState: "No fractal structures mapped. Begin recursive exploration.",
    vibe: "mandelbrot-explorer",
  },
  game: {
    accent: "#D500F9",
    secondaryAccent: "#E040FB",
    icon: "🎮",
    gradient: "linear-gradient(135deg, #D500F911, #E040FB11)",
    contentLayout: "gallery",
    cardStyle: "game",
    emptyState: "No games in library. Add your first title.",
    vibe: "steam-library",
  },
  "game-design": {
    accent: "#6200EA",
    secondaryAccent: "#B388FF",
    icon: "🎲",
    gradient: "linear-gradient(135deg, #6200EA11, #B388FF11)",
    contentLayout: "specs",
    cardStyle: "project",
    emptyState: "No game design docs. Draft your first GDD.",
    vibe: "unity-editor",
  },
  geology: {
    accent: "#795548",
    secondaryAccent: "#BCAAA4",
    icon: "🪨",
    gradient: "linear-gradient(135deg, #79554811, #BCAAA411)",
    contentLayout: "reference",
    cardStyle: "paper",
    emptyState: "No geological surveys. Start mapping formations.",
    vibe: "usgs-fieldwork",
  },
  global: {
    accent: "#0097A7",
    secondaryAccent: "#80DEEA",
    icon: "🌐",
    gradient: "linear-gradient(135deg, #0097A711, #80DEEA11)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No global metrics configured. Add world indicators.",
    vibe: "un-data-portal",
  },
  goals: {
    accent: "#FF6D00",
    secondaryAccent: "#FFAB40",
    icon: "🎯",
    gradient: "linear-gradient(135deg, #FF6D0011, #FFAB4011)",
    contentLayout: "feed",
    cardStyle: "project",
    emptyState: "No goals set. Define your first objective.",
    vibe: "okr-tracker",
  },
  government: {
    accent: "#283593",
    secondaryAccent: "#7986CB",
    icon: "🏛️",
    gradient: "linear-gradient(135deg, #28359311, #7986CB11)",
    contentLayout: "document",
    cardStyle: "document",
    emptyState: "No policies or regulations added.",
    vibe: "govuk-civic",
  },
  graph: {
    accent: "#304FFE",
    secondaryAccent: "#8C9EFF",
    icon: "📊",
    gradient: "linear-gradient(135deg, #304FFE11, #8C9EFF11)",
    contentLayout: "data",
    cardStyle: "component",
    emptyState: "No graph data. Add nodes and edges to explore.",
    vibe: "neo4j-visualizer",
  },
  grounding: {
    accent: "#4E342E",
    secondaryAccent: "#A1887F",
    icon: "🌱",
    gradient: "linear-gradient(135deg, #4E342E11, #A1887F11)",
    contentLayout: "feed",
    cardStyle: "post",
    emptyState: "No grounding exercises logged. Take a mindful moment.",
    vibe: "mindfulness-journal",
  },
  "home-improvement": {
    accent: "#F57F17",
    secondaryAccent: "#FFF176",
    icon: "🏠",
    gradient: "linear-gradient(135deg, #F57F1711, #FFF17611)",
    contentLayout: "tutorial",
    cardStyle: "project",
    emptyState: "No home projects started. Plan your first improvement.",
    vibe: "homedepot-projects",
  },
  household: {
    accent: "#8BC34A",
    secondaryAccent: "#DCEDC8",
    icon: "🏡",
    gradient: "linear-gradient(135deg, #8BC34A11, #DCEDC811)",
    contentLayout: "feed",
    cardStyle: "listing",
    emptyState: "No household tasks tracked. Organize your home life.",
    vibe: "homekit-tasks",
  },
  hr: {
    accent: "#00838F",
    secondaryAccent: "#80DEEA",
    icon: "👥",
    gradient: "linear-gradient(135deg, #00838F11, #80DEEA11)",
    contentLayout: "data",
    cardStyle: "metric",
    emptyState: "No employee records. Add your first team member.",
    vibe: "workday-portal",
  },
  hvac: {
    accent: "#0D47A1",
    secondaryAccent: "#90CAF9",
    icon: "❄️",
    gradient: "linear-gradient(135deg, #0D47A111, #90CAF911)",
    contentLayout: "tutorial",
    cardStyle: "project",
    emptyState: "No HVAC systems registered. Add equipment to track.",
    vibe: "carrier-systems",
  },
  hypothesis: {
    accent: "#9C27B0",
    secondaryAccent: "#CE93D8",
    icon: "🔬",
    gradient: "linear-gradient(135deg, #9C27B011, #CE93D811)",
    contentLayout: "paper",
    cardStyle: "paper",
    emptyState: "No hypotheses formed. Propose something testable.",
    vibe: "arxiv-preprint",
  },
  "import": {
    accent: "#00695C",
    secondaryAccent: "#80CBC4",
    icon: "📥",
    gradient: "linear-gradient(135deg, #00695C11, #80CBC411)",
    contentLayout: "data",
    cardStyle: "component",
    emptyState: "No imports configured. Set up your first data source.",
    vibe: "data-pipeline",
  },
  inference: {
    accent: "#311B92",
    secondaryAccent: "#B39DDB",
    icon: "🧩",
    gradient: "linear-gradient(135deg, #311B9211, #B39DDB11)",
    contentLayout: "ide",
    cardStyle: "component",
    emptyState: "No inference pipelines. Build your first model chain.",
    vibe: "jupyter-notebook",
  },
  ingest: {
    accent: "#006064",
    secondaryAccent: "#80DEEA",
    icon: "📡",
    gradient: "linear-gradient(135deg, #00606411, #80DEEA11)",
    contentLayout: "data",
    cardStyle: "metric",
    emptyState: "No ingestion feeds active. Connect a data source.",
    vibe: "kafka-streams",
  },
  insurance: {
    accent: "#1565C0",
    secondaryAccent: "#90CAF9",
    icon: "🛡️",
    gradient: "linear-gradient(135deg, #1565C011, #90CAF911)",
    contentLayout: "document",
    cardStyle: "document",
    emptyState: "No policies tracked. Add insurance records.",
    vibe: "geico-claims",
  },
  integrations: {
    accent: "#4527A0",
    secondaryAccent: "#B39DDB",
    icon: "🔌",
    gradient: "linear-gradient(135deg, #4527A011, #B39DDB11)",
    contentLayout: "data",
    cardStyle: "component",
    emptyState: "No integrations connected. Link your first service.",
    vibe: "zapier-flows",
  },
  invariant: {
    accent: "#880E4F",
    secondaryAccent: "#F48FB1",
    icon: "🔒",
    gradient: "linear-gradient(135deg, #880E4F11, #F48FB111)",
    contentLayout: "specs",
    cardStyle: "document",
    emptyState: "No invariants defined. Specify system constraints.",
    vibe: "formal-verification",
  },
  lab: {
    accent: "#00BFA5",
    secondaryAccent: "#A7FFEB",
    icon: "🧪",
    gradient: "linear-gradient(135deg, #00BFA511, #A7FFEB11)",
    contentLayout: "paper",
    cardStyle: "paper",
    emptyState: "No experiments logged. Start your lab notebook.",
    vibe: "labarchives-bench",
  },
  landscaping: {
    accent: "#33691E",
    secondaryAccent: "#AED581",
    icon: "🌳",
    gradient: "linear-gradient(135deg, #33691E11, #AED58111)",
    contentLayout: "tutorial",
    cardStyle: "project",
    emptyState: "No landscaping projects. Design your outdoor space.",
    vibe: "landscaping-pro",
  },
  law: {
    accent: "#3E2723",
    secondaryAccent: "#8D6E63",
    icon: "⚖️",
    gradient: "linear-gradient(135deg, #3E272311, #8D6E6311)",
    contentLayout: "document",
    cardStyle: "document",
    emptyState: "No cases filed. Begin your legal research.",
    vibe: "westlaw-research",
  },
  projects: {
    accent: "#FF6F00",
    secondaryAccent: "#FFB300",
    icon: "📂",
    gradient: "linear-gradient(135deg, #FF6F0011, #FFB30011)",
    contentLayout: "feed",
    cardStyle: "project",
    emptyState: "No projects created. Kick off your first initiative.",
    vibe: "asana-projects",
  },
  quantum: {
    accent: "#6200EA",
    secondaryAccent: "#B388FF",
    icon: "⚛️",
    gradient: "linear-gradient(135deg, #6200EA11, #B388FF11)",
    contentLayout: "paper",
    cardStyle: "paper",
    emptyState: "No quantum circuits designed. Enter the quantum realm.",
    vibe: "ibm-quantum",
  },
  queue: {
    accent: "#455A64",
    secondaryAccent: "#78909C",
    icon: "📬",
    gradient: "linear-gradient(135deg, #455A6411, #78909C11)",
    contentLayout: "data",
    cardStyle: "component",
    emptyState: "No queues configured. Set up your message pipeline.",
    vibe: "rabbitmq-manager",
  },
  realestate: {
    accent: "#00695C",
    secondaryAccent: "#4DB6AC",
    icon: "🏘️",
    gradient: "linear-gradient(135deg, #00695C11, #4DB6AC11)",
    contentLayout: "feed",
    cardStyle: "listing",
    emptyState: "No properties listed. Add your first real estate asset.",
    vibe: "zillow-listings",
  },
  reasoning: {
    accent: "#4527A0",
    secondaryAccent: "#9575CD",
    icon: "🧠",
    gradient: "linear-gradient(135deg, #4527A011, #9575CD11)",
    contentLayout: "document",
    cardStyle: "paper",
    emptyState: "No arguments mapped. Build your first logical proof.",
    vibe: "logic-workbench",
  },
  reflection: {
    accent: "#6D4C41",
    secondaryAccent: "#A1887F",
    icon: "🪞",
    gradient: "linear-gradient(135deg, #6D4C4111, #A1887F11)",
    contentLayout: "feed",
    cardStyle: "post",
    emptyState: "No reflections recorded. Pause and think deeply.",
    vibe: "journaling-app",
  },
  repos: {
    accent: "#24292E",
    secondaryAccent: "#586069",
    icon: "📦",
    gradient: "linear-gradient(135deg, #24292E11, #58606911)",
    contentLayout: "ide",
    cardStyle: "repo",
    emptyState: "No repositories tracked. Connect your codebase.",
    vibe: "github-repos",
  },
  resonance: {
    accent: "#D81B60",
    secondaryAccent: "#F06292",
    icon: "🎵",
    gradient: "linear-gradient(135deg, #D81B6011, #F0629211)",
    contentLayout: "player",
    cardStyle: "track",
    emptyState: "No resonance patterns found. Tune your signal.",
    vibe: "resonance-wave",
  },
  retail: {
    accent: "#E91E63",
    secondaryAccent: "#F48FB1",
    icon: "🛍️",
    gradient: "linear-gradient(135deg, #E91E6311, #F48FB111)",
    contentLayout: "feed",
    cardStyle: "listing",
    emptyState: "No products listed. Stock your first shelf.",
    vibe: "shopify-store",
  },
  schema: {
    accent: "#37474F",
    secondaryAccent: "#607D8B",
    icon: "🗂️",
    gradient: "linear-gradient(135deg, #37474F11, #607D8B11)",
    contentLayout: "specs",
    cardStyle: "component",
    emptyState: "No schemas defined. Model your first data structure.",
    vibe: "json-schema",
  },
  services: {
    accent: "#00897B",
    secondaryAccent: "#4DB6AC",
    icon: "🛠️",
    gradient: "linear-gradient(135deg, #00897B11, #4DB6AC11)",
    contentLayout: "feed",
    cardStyle: "listing",
    emptyState: "No services cataloged. Register your offerings.",
    vibe: "service-catalog",
  },
  sim: {
    accent: "#7C4DFF",
    secondaryAccent: "#B388FF",
    icon: "🎰",
    gradient: "linear-gradient(135deg, #7C4DFF11, #B388FF11)",
    contentLayout: "isometric",
    cardStyle: "project",
    emptyState: "No simulations configured. Model your first scenario.",
    vibe: "unity-sim",
  },
  srs: {
    accent: "#0288D1",
    secondaryAccent: "#4FC3F7",
    icon: "🗃️",
    gradient: "linear-gradient(135deg, #0288D111, #4FC3F711)",
    contentLayout: "course",
    cardStyle: "lesson",
    emptyState: "No flashcard decks created. Start memorizing.",
    vibe: "anki-decks",
  },
  suffering: {
    accent: "#B71C1C",
    secondaryAccent: "#E57373",
    icon: "💔",
    gradient: "linear-gradient(135deg, #B71C1C11, #E5737311)",
    contentLayout: "feed",
    cardStyle: "post",
    emptyState: "No support entries. You're not alone.",
    vibe: "crisis-support",
  },
  supplychain: {
    accent: "#EF6C00",
    secondaryAccent: "#FFB74D",
    icon: "🔗",
    gradient: "linear-gradient(135deg, #EF6C0011, #FFB74D11)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No supply chain data. Track your logistics pipeline.",
    vibe: "sap-supply",
  },
  telecommunications: {
    accent: "#0277BD",
    secondaryAccent: "#4FC3F7",
    icon: "📡",
    gradient: "linear-gradient(135deg, #0277BD11, #4FC3F711)",
    contentLayout: "dashboard",
    cardStyle: "metric",
    emptyState: "No telecom networks configured. Connect your systems.",
    vibe: "telecom-ops",
  },
  temporal: {
    accent: "#5E35B1",
    secondaryAccent: "#9575CD",
    icon: "⏳",
    gradient: "linear-gradient(135deg, #5E35B111, #9575CD11)",
    contentLayout: "data",
    cardStyle: "metric",
    emptyState: "No temporal data tracked. Map your timeline.",
    vibe: "time-series",
  },
  thread: {
    accent: "#3949AB",
    secondaryAccent: "#7986CB",
    icon: "🧵",
    gradient: "linear-gradient(135deg, #3949AB11, #7986CB11)",
    contentLayout: "threads",
    cardStyle: "thread",
    emptyState: "No threads started. Begin a conversation.",
    vibe: "reddit-threads",
  },
  tick: {
    accent: "#607D8B",
    secondaryAccent: "#90A4AE",
    icon: "⏱️",
    gradient: "linear-gradient(135deg, #607D8B11, #90A4AE11)",
    contentLayout: "data",
    cardStyle: "metric",
    emptyState: "No tick events configured. Set up your scheduler.",
    vibe: "cron-scheduler",
  },
  timeline: {
    accent: "#8E24AA",
    secondaryAccent: "#CE93D8",
    icon: "📅",
    gradient: "linear-gradient(135deg, #8E24AA11, #CE93D811)",
    contentLayout: "data",
    cardStyle: "project",
    emptyState: "No timeline events. Plot your first milestone.",
    vibe: "timeline-js",
  },
  transfer: {
    accent: "#00838F",
    secondaryAccent: "#4DD0E1",
    icon: "🔄",
    gradient: "linear-gradient(135deg, #00838F11, #4DD0E111)",
    contentLayout: "data",
    cardStyle: "component",
    emptyState: "No transfers logged. Move data between systems.",
    vibe: "wire-transfer",
  },
  "urban-planning": {
    accent: "#546E7A",
    secondaryAccent: "#90A4AE",
    icon: "🏙️",
    gradient: "linear-gradient(135deg, #546E7A11, #90A4AE11)",
    contentLayout: "isometric",
    cardStyle: "district",
    emptyState: "No urban zones defined. Design your city layout.",
    vibe: "simcity-planner",
  },
  veterinary: {
    accent: "#4CAF50",
    secondaryAccent: "#81C784",
    icon: "🐾",
    gradient: "linear-gradient(135deg, #4CAF5011, #81C78411)",
    contentLayout: "feed",
    cardStyle: "clinical",
    emptyState: "No animal patients. Register your first case.",
    vibe: "vet-clinic",
  },
  voice: {
    accent: "#7B1FA2",
    secondaryAccent: "#BA68C8",
    icon: "🎙️",
    gradient: "linear-gradient(135deg, #7B1FA211, #BA68C811)",
    contentLayout: "player",
    cardStyle: "track",
    emptyState: "No voice recordings. Capture your first audio.",
    vibe: "podcast-studio",
  },
  vote: {
    accent: "#1565C0",
    secondaryAccent: "#64B5F6",
    icon: "🗳️",
    gradient: "linear-gradient(135deg, #1565C011, #64B5F611)",
    contentLayout: "feed",
    cardStyle: "post",
    emptyState: "No votes cast. Create your first poll.",
    vibe: "ballot-box",
  },
  welding: {
    accent: "#E65100",
    secondaryAccent: "#FF8A65",
    icon: "🔥",
    gradient: "linear-gradient(135deg, #E6510011, #FF8A6511)",
    contentLayout: "tutorial",
    cardStyle: "project",
    emptyState: "No welding projects. Fire up your first joint.",
    vibe: "welding-shop",
  },
  whiteboard: {
    accent: "#26C6DA",
    secondaryAccent: "#80DEEA",
    icon: "🖊️",
    gradient: "linear-gradient(135deg, #26C6DA11, #80DEEA11)",
    contentLayout: "gallery",
    cardStyle: "artwork",
    emptyState: "No whiteboard sketches. Draw your first idea.",
    vibe: "miro-canvas",
  },
};

// Fallback for lenses without a defined identity
export const DEFAULT_IDENTITY: LensIdentity = {
  accent: "#5B8DEF",
  secondaryAccent: "#9B978F",
  icon: "\u{1F50D}",
  gradient: "linear-gradient(135deg, #5B8DEF11, #9B978F11)",
  contentLayout: "feed",
  cardStyle: "default",
  emptyState: "No content yet.",
  vibe: "default",
};

/**
 * Get identity for a lens, falling back to DEFAULT_IDENTITY.
 */
export function getLensIdentity(domain: string): LensIdentity {
  return LENS_IDENTITIES[domain] || DEFAULT_IDENTITY;
}
