/**
 * Canonical Lens Registry — single source of truth for all lens metadata.
 *
 * Fixes FE-001 (discoverability), FE-007 (command palette), FE-008 (sidebar drift).
 * Implements FE-030: Core Lens Consolidation.
 *
 * Every lens route MUST have an entry here. The sidebar, command palette,
 * and route validation script all read from this registry.
 *
 * CONSOLIDATION MODEL:
 * Five core lenses (Chat, Board, Graph, Code, Studio) serve as primary
 * workspaces. Related lenses are "absorbed" into a core lens as sub-tabs,
 * keeping their routes but being navigable from within the parent.
 * Everything else is an Extension — hidden by default, discoverable on demand.
 */

import {
  MessageSquare,
  MessageCircle,
  Code,
  FlaskConical,
  Store,
  FileText,
  Book,
  Layout,
  Calendar,
  Share2,
  Sparkles,
  Target,
  Activity,
  Users,
  User,
  Dna,
  Atom,
  Orbit,
  DollarSign,
  Gamepad2,
  Glasses,
  Newspaper,
  Music,
  Brain,
  Wand2,
  Hash,
  Rss,
  FolderGit2,
  Heart,
  Shield,
  Database,
  FileCode,
  Globe,
  Cpu,
  GitFork,
  Scale,
  Lock,
  Layers,
  Lightbulb,
  Microscope,
  Beaker,
  Compass,
  Terminal,
  Wallet,
  Eye,
  Workflow,
  BookOpen,
  Network,
  Headphones,
  Vote,
  PenTool,
  Boxes,
  Clock,
  Zap,
  Upload,
  Download,
  AlertTriangle,
  Rocket,
  Puzzle,
  Stethoscope,
  Wrench,
  UtensilsCrossed,
  ShoppingCart,
  Home,
  Calculator,
  Wheat,
  Truck,
  GraduationCap,
  Briefcase,
  HeartHandshake,
  Building2,
  Dumbbell,
  Palette,
  Factory,
  TreePine,
  Landmark,
  Plane,
  PartyPopper,
  FlaskRound,
  ShieldCheck,
  Scissors,
  Umbrella,
  Shirt,
  ChefHat,
  Baby,
  PawPrint,
  Trophy,
  Hammer,
  Swords,
  BadgeCheck,
  HardHat,
  Plug,
  Mountain,
  Radio,
  Play,
  Camera,
  TrendingUp,
  Bot,
  Pill,
  Map as MapIcon,
  Search,
  Gem,
  Link2,
  Waves,
  Wind,
  MapPin,
  Cog,
  type LucideIcon,
} from 'lucide-react';

export type LensCategory =
  | 'core'
  | 'knowledge'
  | 'science'
  | 'creative'
  | 'governance'
  | 'ai'
  | 'system'
  | 'specialized'
  | 'superlens';

export interface LensEntry {
  /** Unique identifier matching the route directory name */
  id: string;
  /** Display name */
  name: string;
  /** Lucide icon component */
  icon: LucideIcon;
  /** Short description for command palette / tooltips */
  description: string;
  /** Grouping category */
  category: LensCategory;
  /** Whether to show in sidebar navigation */
  showInSidebar: boolean;
  /** Whether to show in command palette */
  showInCommandPalette: boolean;
  /** Route path */
  path: string;
  /** Sort order within category (lower = higher) */
  order: number;
  /** Keywords for search */
  keywords?: string[];
  /** If set, this lens is absorbed into the specified core lens as a sub-tab */
  coreLens?: CoreLensId;
  /** Display label when shown as a sub-tab inside a core lens */
  tabLabel?: string;
}

// ── Core Lens Consolidation ──────────────────────────────────────

/** The five primary workspace lenses */
export type CoreLensId = 'chat' | 'board' | 'graph' | 'code' | 'studio';

export interface CoreLensConfig {
  id: CoreLensId;
  name: string;
  icon: LucideIcon;
  description: string;
  tagline: string;
  path: string;
  color: string;
  /** IDs of lenses absorbed into this core lens */
  absorbedLensIds: string[];
}

/**
 * The 5 core lenses and their consolidation mapping.
 * Each core lens absorbs related lenses as sub-tabs/modes.
 */
export const CORE_LENSES: CoreLensConfig[] = [
  {
    id: 'chat',
    name: 'Chat',
    icon: MessageSquare,
    description: 'AI conversations, forums, governance discussions, and daily notes',
    tagline: 'Think out loud',
    path: '/lenses/chat',
    color: 'neon-cyan',
    absorbedLensIds: ['thread', 'forum', 'daily', 'council', 'anon', 'voice', 'feed', 'news'],
  },
  {
    id: 'board',
    name: 'Board',
    icon: Layout,
    description: 'Tasks, goals, calendar, timeline, and spaced repetition',
    tagline: 'Get things done',
    path: '/lenses/board',
    color: 'neon-purple',
    absorbedLensIds: ['goals', 'calendar', 'timeline', 'srs', 'whiteboard'],
  },
  {
    id: 'graph',
    name: 'Graph',
    icon: Share2,
    description: 'Knowledge graph, schemas, entities, and ecosystem mapping',
    tagline: 'Connect everything',
    path: '/lenses/graph',
    color: 'neon-green',
    absorbedLensIds: ['schema', 'entity', 'temporal', 'eco', 'meta'],
  },
  {
    id: 'code',
    name: 'Code',
    icon: Code,
    description: 'Editor, debugger, database explorer, and repository browser',
    tagline: 'Build and ship',
    path: '/lenses/code',
    color: 'neon-blue',
    absorbedLensIds: ['debug', 'database', 'repos'],
  },
  {
    id: 'studio',
    name: 'Studio',
    icon: Music,
    description: 'Music production, visual art, game dev, and creative tools',
    tagline: 'Create anything',
    path: '/lenses/studio',
    color: 'neon-pink',
    absorbedLensIds: ['music', 'art', 'fractal', 'game', 'sim', 'ar', 'podcast'],
  },
];

/** Set of all core lens IDs for quick lookup */
const CORE_LENS_IDS = new Set<string>(CORE_LENSES.map((c) => c.id));

/** Map from absorbed lens ID to its parent core lens ID */
const ABSORPTION_MAP = new Map<string, CoreLensId>();
for (const core of CORE_LENSES) {
  for (const absorbedId of core.absorbedLensIds) {
    ABSORPTION_MAP.set(absorbedId, core.id);
  }
}

/**
 * Complete lens registry. Every lens under app/lenses/ must be listed here.
 * New lenses should be added to this array — sidebar and command palette
 * are generated automatically.
 */
export const LENS_REGISTRY: LensEntry[] = [
  // ── Platform ────────────────────────────────────────────────────
  {
    id: 'global',
    name: 'Global',
    icon: Globe,
    description: 'Browse all DTUs, artifacts, jobs, marketplace',
    category: 'core',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/global',
    order: 0,
    keywords: ['browse', 'all', 'truth', 'global', 'everything'],
  },
  {
    id: 'hub',
    name: 'Lens Hub',
    icon: Compass,
    description: 'Discover all lenses',
    category: 'core',
    showInSidebar: true,
    showInCommandPalette: true,
    path: '/hub',
    order: 0,
    keywords: ['all', 'lenses', 'discover', 'hub', 'browse'],
  },

  // ── Core 5 ──────────────────────────────────────────────────────
  {
    id: 'chat',
    name: 'Chat',
    icon: MessageSquare,
    description: 'AI conversations, forums, and daily notes',
    category: 'core',
    showInSidebar: true,
    showInCommandPalette: true,
    path: '/lenses/chat',
    order: 1,
    keywords: ['message', 'talk', 'ai', 'forum', 'daily'],
  },
  {
    id: 'board',
    name: 'Board',
    icon: Layout,
    description: 'Tasks, goals, calendar, and planning',
    category: 'core',
    showInSidebar: true,
    showInCommandPalette: true,
    path: '/lenses/board',
    order: 2,
    keywords: ['kanban', 'tasks', 'project', 'goals', 'calendar'],
  },
  {
    id: 'graph',
    name: 'Graph',
    icon: Share2,
    description: 'Knowledge graph and entity exploration',
    category: 'core',
    showInSidebar: true,
    showInCommandPalette: true,
    path: '/lenses/graph',
    order: 3,
    keywords: ['network', 'nodes', 'edges', 'knowledge', 'schema'],
  },
  {
    id: 'code',
    name: 'Code',
    icon: Code,
    description: 'Editor, debugger, and repository browser',
    category: 'core',
    showInSidebar: true,
    showInCommandPalette: true,
    path: '/lenses/code',
    order: 4,
    keywords: ['editor', 'programming', 'dev', 'debug', 'database'],
  },
  {
    id: 'studio',
    name: 'Studio',
    icon: Music,
    description: 'Music, art, game dev, and creative production',
    category: 'core',
    showInSidebar: true,
    showInCommandPalette: true,
    path: '/lenses/studio',
    order: 5,
    keywords: ['production', 'audio', 'mix', 'master', 'art', 'music'],
  },
  {
    id: 'dtus',
    name: 'DTU Browser',
    icon: Database,
    description: 'Browse, search, and manage Discrete Thought Units',
    category: 'knowledge',
    showInSidebar: true,
    showInCommandPalette: true,
    path: '/lenses/dtus',
    order: 6,
    keywords: ['dtu', 'browse', 'search', 'thoughts', 'knowledge', 'units'],
  },

  // ── Absorbed into Chat ──────────────────────────────────────────
  {
    id: 'thread',
    name: 'Threads',
    icon: MessageCircle,
    description: 'Threaded conversations',
    category: 'core',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/thread',
    order: 10,
    keywords: ['conversation', 'discussion'],
    coreLens: 'chat',
    tabLabel: 'Threads',
  },
  {
    id: 'forum',
    name: 'Forum',
    icon: Hash,
    description: 'Discussion forum',
    category: 'knowledge',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/forum',
    order: 11,
    keywords: ['discuss', 'community'],
    coreLens: 'chat',
    tabLabel: 'Forum',
  },
  {
    id: 'daily',
    name: 'Daily',
    icon: BookOpen,
    description: 'Daily notes and journal',
    category: 'knowledge',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/daily',
    order: 12,
    keywords: ['journal', 'notes', 'diary'],
    coreLens: 'chat',
    tabLabel: 'Daily',
  },
  {
    id: 'council',
    name: 'Council',
    icon: Users,
    description: 'DTU governance council',
    category: 'governance',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/council',
    order: 13,
    keywords: ['vote', 'governance', 'decisions'],
    coreLens: 'chat',
    tabLabel: 'Governance',
  },
  {
    id: 'anon',
    name: 'Anon',
    icon: User,
    description: 'Anonymous messaging',
    category: 'governance',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/anon',
    order: 14,
    keywords: ['anonymous', 'private'],
    coreLens: 'chat',
    tabLabel: 'Anonymous',
  },
  {
    id: 'voice',
    name: 'Voice',
    icon: Headphones,
    description: 'Voice input and TTS',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/voice',
    order: 15,
    keywords: ['audio', 'speech', 'microphone'],
    coreLens: 'chat',
    tabLabel: 'Voice',
  },
  {
    id: 'feed',
    name: 'Feed',
    icon: Rss,
    description: 'RSS and content feed',
    category: 'knowledge',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/feed',
    order: 16,
    keywords: ['rss', 'news', 'content'],
    coreLens: 'chat',
    tabLabel: 'Feed',
  },
  {
    id: 'news',
    name: 'News',
    icon: Newspaper,
    description: 'News aggregation',
    category: 'knowledge',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/news',
    order: 17,
    keywords: ['articles', 'headlines'],
    coreLens: 'chat',
    tabLabel: 'News',
  },

  // ── Absorbed into Board ─────────────────────────────────────────
  {
    id: 'goals',
    name: 'Goals',
    icon: Target,
    description: 'Goal tracking and planning',
    category: 'knowledge',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/goals',
    order: 20,
    keywords: ['objectives', 'planning', 'targets'],
    coreLens: 'board',
    tabLabel: 'Goals',
  },
  {
    id: 'calendar',
    name: 'Calendar',
    icon: Calendar,
    description: 'Calendar and scheduling',
    category: 'knowledge',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/calendar',
    order: 21,
    keywords: ['schedule', 'events', 'dates'],
    coreLens: 'board',
    tabLabel: 'Calendar',
  },
  {
    id: 'timeline',
    name: 'Timeline',
    icon: Heart,
    description: 'Chronological timeline',
    category: 'knowledge',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/timeline',
    order: 22,
    keywords: ['history', 'chronological'],
    coreLens: 'board',
    tabLabel: 'Timeline',
  },
  {
    id: 'srs',
    name: 'SRS',
    icon: Layers,
    description: 'Spaced repetition study',
    category: 'knowledge',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/srs',
    order: 23,
    keywords: ['study', 'flashcards', 'memory'],
    coreLens: 'board',
    tabLabel: 'Study',
  },
  {
    id: 'whiteboard',
    name: 'Whiteboard',
    icon: PenTool,
    description: 'Freeform whiteboard',
    category: 'knowledge',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/whiteboard',
    order: 24,
    keywords: ['draw', 'diagram', 'sketch'],
    coreLens: 'board',
    tabLabel: 'Whiteboard',
  },

  // ── Absorbed into Graph ─────────────────────────────────────────
  {
    id: 'schema',
    name: 'Schema',
    icon: FileCode,
    description: 'Schema management',
    category: 'system',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/schema',
    order: 30,
    keywords: ['types', 'validation', 'structure'],
    coreLens: 'graph',
    tabLabel: 'Schema',
  },
  {
    id: 'entity',
    name: 'Entity',
    icon: Boxes,
    description: 'World model entity browser',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/entity',
    order: 31,
    keywords: ['world', 'model', 'object'],
    coreLens: 'graph',
    tabLabel: 'Entities',
  },
  {
    id: 'temporal',
    name: 'Temporal',
    icon: Clock,
    description: 'Temporal reasoning',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/temporal',
    order: 32,
    keywords: ['time', 'chronology', 'sequence'],
    coreLens: 'graph',
    tabLabel: 'Temporal',
  },
  {
    id: 'eco',
    name: 'Eco',
    icon: Globe,
    description: 'Ecosystem overview',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/eco',
    order: 33,
    keywords: ['ecosystem', 'environment'],
    coreLens: 'graph',
    tabLabel: 'Ecosystem',
  },
  {
    id: 'meta',
    name: 'Meta',
    icon: Eye,
    description: 'System meta-information',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/meta',
    order: 34,
    keywords: ['about', 'info', 'system'],
    coreLens: 'graph',
    tabLabel: 'Meta',
  },

  // ── Absorbed into Code ──────────────────────────────────────────
  {
    id: 'debug',
    name: 'Debug',
    icon: Terminal,
    description: 'Debug console',
    category: 'system',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/debug',
    order: 40,
    keywords: ['console', 'logs', 'troubleshoot'],
    coreLens: 'code',
    tabLabel: 'Debug',
  },
  {
    id: 'database',
    name: 'Database',
    icon: Database,
    description: 'Database explorer',
    category: 'system',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/database',
    order: 41,
    keywords: ['sql', 'data', 'tables'],
    coreLens: 'code',
    tabLabel: 'Database',
  },
  {
    id: 'repos',
    name: 'Repos',
    icon: FolderGit2,
    description: 'Repository browser',
    category: 'knowledge',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/repos',
    order: 42,
    keywords: ['git', 'repository', 'source'],
    coreLens: 'code',
    tabLabel: 'Repos',
  },

  // ── Absorbed into Studio ────────────────────────────────────────
  {
    id: 'music',
    name: 'Music',
    icon: Music,
    description: 'Music creation tools',
    category: 'creative',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/music',
    order: 50,
    keywords: ['audio', 'composition', 'sound'],
    coreLens: 'studio',
    tabLabel: 'Music',
  },
  {
    id: 'art',
    name: 'Art',
    icon: Palette,
    description: 'Visual art creation and gallery',
    category: 'creative',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/art',
    order: 51,
    keywords: ['artwork', 'gallery', 'visual', 'illustration'],
    coreLens: 'studio',
    tabLabel: 'Art',
  },
  {
    id: 'fractal',
    name: 'Fractal',
    icon: Sparkles,
    description: 'Fractal explorer',
    category: 'creative',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/fractal',
    order: 52,
    keywords: ['visualization', 'patterns', 'generative'],
    coreLens: 'studio',
    tabLabel: 'Visuals',
  },
  {
    id: 'game',
    name: 'Game',
    icon: Gamepad2,
    description: 'Game development',
    category: 'creative',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/game',
    order: 53,
    keywords: ['gaming', 'development'],
    coreLens: 'studio',
    tabLabel: 'Game',
  },
  {
    id: 'sim',
    name: 'Sim',
    icon: Boxes,
    description: 'Simulation sandbox',
    category: 'creative',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/sim',
    order: 54,
    keywords: ['simulation', 'sandbox', 'worldmodel'],
    coreLens: 'studio',
    tabLabel: 'Simulation',
  },
  {
    id: 'ar',
    name: 'AR',
    icon: Glasses,
    description: 'Augmented reality',
    category: 'creative',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/ar',
    order: 55,
    keywords: ['augmented reality', 'webxr', '3d'],
    coreLens: 'studio',
    tabLabel: 'AR',
  },
  {
    id: 'podcast',
    name: 'Podcast',
    icon: Headphones,
    description: 'Podcast creation and distribution',
    category: 'creative',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/podcast',
    order: 56,
    keywords: ['podcast', 'audio', 'episode', 'rss', 'show'],
    coreLens: 'studio',
    tabLabel: 'Podcast',
  },

  // ── Extensions: Platform & System ───────────────────────────────
  {
    id: 'resonance',
    name: 'Resonance',
    icon: Activity,
    description: 'System health dashboard',
    category: 'core',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/resonance',
    order: 100,
    keywords: ['health', 'metrics', 'status'],
  },
  {
    id: 'docs',
    name: 'Docs',
    icon: Book,
    description: 'Documentation viewer',
    category: 'core',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/docs',
    order: 101,
    keywords: ['documentation', 'reference', 'help'],
  },
  {
    id: 'paper',
    name: 'Paper',
    icon: FileText,
    description: 'Research paper editor',
    category: 'core',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/paper',
    order: 102,
    keywords: ['research', 'writing', 'academic'],
  },
  {
    id: 'platform',
    name: 'Platform',
    icon: Activity,
    description: 'Mega platform dashboard',
    category: 'system',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/platform',
    order: 103,
    keywords: [
      'pipeline',
      'empirical',
      'bridge',
      'beacon',
      'scope',
      'nerve',
      'monitor',
      'dashboard',
      'platform',
    ],
  },
  {
    id: 'admin',
    name: 'Admin',
    icon: Shield,
    description: 'System administration',
    category: 'system',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/admin',
    order: 104,
    keywords: ['settings', 'configuration', 'manage'],
  },
  {
    id: 'audit',
    name: 'Audit',
    icon: Eye,
    description: 'Audit log viewer',
    category: 'system',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/audit',
    order: 105,
    keywords: ['log', 'history', 'trail'],
  },
  {
    id: 'integrations',
    name: 'Integrations',
    icon: Puzzle,
    description: 'Third-party integrations',
    category: 'system',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/integrations',
    order: 106,
    keywords: ['connect', 'api', 'external'],
  },
  {
    id: 'queue',
    name: 'Queue',
    icon: Layers,
    description: 'Job queue monitor',
    category: 'system',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/queue',
    order: 107,
    keywords: ['jobs', 'workers', 'background'],
  },
  {
    id: 'tick',
    name: 'Tick',
    icon: Clock,
    description: 'System tick monitor',
    category: 'system',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/tick',
    order: 108,
    keywords: ['heartbeat', 'pulse', 'cycle'],
  },
  {
    id: 'lock',
    name: 'Lock',
    icon: Lock,
    description: 'Sovereignty lock status',
    category: 'system',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/lock',
    order: 109,
    keywords: ['sovereignty', '70%', 'control'],
  },
  {
    id: 'offline',
    name: 'Offline',
    icon: Download,
    description: 'Offline data manager',
    category: 'system',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/offline',
    order: 110,
    keywords: ['local', 'sync', 'cache'],
  },

  // ── Extensions: Governance & Economy ────────────────────────────
  {
    id: 'market',
    name: 'Market',
    icon: Store,
    description: 'DTU marketplace',
    category: 'governance',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/market',
    order: 120,
    keywords: ['trade', 'exchange'],
  },
  {
    id: 'marketplace',
    name: 'Marketplace',
    icon: Store,
    description: 'Plugin marketplace',
    category: 'governance',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/marketplace',
    order: 121,
    keywords: ['plugins', 'extensions', 'store'],
  },
  {
    id: 'questmarket',
    name: 'Questmarket',
    icon: Target,
    description: 'Bounty and quest system',
    category: 'governance',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/questmarket',
    order: 122,
    keywords: ['bounty', 'quest', 'rewards'],
  },
  {
    id: 'vote',
    name: 'Vote',
    icon: Vote,
    description: 'Voting system',
    category: 'governance',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/vote',
    order: 123,
    keywords: ['poll', 'election', 'ballot'],
  },
  {
    id: 'ethics',
    name: 'Ethics',
    icon: Scale,
    description: 'Ethics and alignment review',
    category: 'governance',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/ethics',
    order: 124,
    keywords: ['alignment', 'values', 'moral'],
  },
  {
    id: 'alliance',
    name: 'Alliance',
    icon: Users,
    description: 'Alliance management',
    category: 'governance',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/alliance',
    order: 125,
    keywords: ['group', 'collaboration', 'team'],
  },
  {
    id: 'billing',
    name: 'Billing',
    icon: Wallet,
    description: 'Billing and credits',
    category: 'governance',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/billing',
    order: 126,
    keywords: ['payment', 'credits', 'wallet'],
  },
  {
    id: 'crypto',
    name: 'Crypto',
    icon: Lock,
    description: 'Cryptography tools',
    category: 'governance',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/crypto',
    order: 127,
    keywords: ['encryption', 'keys', 'security'],
  },

  // ── Extensions: Science ─────────────────────────────────────────
  {
    id: 'bio',
    name: 'Bio',
    icon: Dna,
    description: 'Biology tools',
    category: 'science',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/bio',
    order: 130,
    keywords: ['biology', 'genetics', 'life'],
  },
  {
    id: 'chem',
    name: 'Chem',
    icon: Atom,
    description: 'Chemistry tools',
    category: 'science',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/chem',
    order: 131,
    keywords: ['chemistry', 'molecules', 'elements'],
  },
  {
    id: 'physics',
    name: 'Physics',
    icon: Orbit,
    description: 'Physics simulations',
    category: 'science',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/physics',
    order: 132,
    keywords: ['simulation', 'mechanics', 'quantum'],
  },
  {
    id: 'math',
    name: 'Math',
    icon: Compass,
    description: 'Mathematics tools',
    category: 'science',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/math',
    order: 133,
    keywords: ['calculation', 'algebra', 'geometry'],
  },
  {
    id: 'root',
    name: 'Refusal Algebra',
    icon: Hash,
    description:
      'Base-6 Refusal Algebra numeral system — convert, compute, and explore semantic number theory',
    category: 'science',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/root',
    order: 134,
    keywords: ['base-6', 'refusal algebra', 'glyphs', 'numeral', 'semantic', 'pivot', 'bridge'],
  },
  {
    id: 'quantum',
    name: 'Quantum',
    icon: Cpu,
    description: 'Quantum computing explorer',
    category: 'science',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/quantum',
    order: 134,
    keywords: ['qubit', 'quantum computing'],
  },
  {
    id: 'neuro',
    name: 'Neuro',
    icon: Network,
    description: 'Neuroscience tools',
    category: 'science',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/neuro',
    order: 135,
    keywords: ['brain', 'neuroscience', 'neural'],
  },

  // ── Extensions: AI & Cognition ──────────────────────────────────
  {
    id: 'genesis',
    name: 'Genesis',
    icon: Zap,
    description:
      'Real-time emergent activity — named entities, artifacts, inter-emergent communications, and the live substrate feed',
    category: 'ai',
    showInSidebar: true,
    showInCommandPalette: true,
    path: '/lenses/genesis',
    order: 139,
    keywords: [
      'emergents',
      'genesis',
      'entities',
      'feed',
      'activity',
      'naming',
      'artifacts',
      'communications',
    ],
  },
  {
    id: 'ml',
    name: 'ML',
    icon: Brain,
    description: 'Machine learning tools',
    category: 'ai',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/ml',
    order: 140,
    keywords: ['machine learning', 'training', 'models'],
  },
  {
    id: 'agents',
    name: 'Agents',
    icon: Cpu,
    description: 'AI agent management',
    category: 'ai',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/agents',
    order: 141,
    keywords: ['autonomous', 'bot', 'agent'],
  },
  {
    id: 'reasoning',
    name: 'Reasoning',
    icon: Lightbulb,
    description: 'Reasoning chain builder',
    category: 'ai',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/reasoning',
    order: 142,
    keywords: ['logic', 'inference', 'chain'],
  },
  {
    id: 'hypothesis',
    name: 'Hypothesis',
    icon: Beaker,
    description: 'Hypothesis testing',
    category: 'ai',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/hypothesis',
    order: 143,
    keywords: ['test', 'experiment', 'theory'],
  },
  {
    id: 'research',
    name: 'Research',
    icon: BookOpen,
    description: 'Full-text search across DTUs',
    category: 'knowledge',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/research',
    order: 115,
    keywords: ['search', 'find', 'query', 'explore'],
  },
  {
    id: 'answers',
    name: 'The Answers',
    icon: Sparkles,
    description: 'Browse the 30 hard-problem/answer pairs of STSVK + Concord',
    category: 'knowledge',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/answers',
    order: 116,
    keywords: ['stsvk', 'framework', 'fixed point', 'manifold', 'oracle', 'hard problems'],
  },
  {
    id: 'cri',
    name: 'CRI',
    icon: Activity,
    description: 'CRETI score analysis',
    category: 'knowledge',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/cri',
    order: 116,
    keywords: ['score', 'quality', 'creti', 'metrics'],
  },
  {
    id: 'ingest',
    name: 'Ingest',
    icon: Upload,
    description: 'Document ingestion & chunking',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/ingest',
    order: 171,
    keywords: ['upload', 'chunk', 'import', 'document'],
  },
  {
    id: 'inference',
    name: 'Inference',
    icon: Workflow,
    description: 'Inference engine',
    category: 'ai',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/inference',
    order: 144,
    keywords: ['deduce', 'rules', 'facts'],
  },
  {
    id: 'metacognition',
    name: 'Metacognition',
    icon: Eye,
    description: 'Self-awareness monitoring',
    category: 'ai',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/metacognition',
    order: 145,
    keywords: ['awareness', 'introspection', 'calibration'],
  },
  {
    id: 'metalearning',
    name: 'Metalearning',
    icon: Rocket,
    description: 'Learning strategy optimization',
    category: 'ai',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/metalearning',
    order: 146,
    keywords: ['strategy', 'optimization', 'learning'],
  },
  {
    id: 'reflection',
    name: 'Reflection',
    icon: Microscope,
    description: 'Self-reflection engine',
    category: 'ai',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/reflection',
    order: 147,
    keywords: ['reflect', 'introspect', 'insight'],
  },
  {
    id: 'affect',
    name: 'Affect',
    icon: Heart,
    description: 'Affect translation spine',
    category: 'ai',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/affect',
    order: 148,
    keywords: ['emotion', 'sentiment', 'feeling'],
  },
  {
    id: 'attention',
    name: 'Attention',
    icon: Zap,
    description: 'Attention management',
    category: 'ai',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/attention',
    order: 149,
    keywords: ['focus', 'priority', 'thread'],
  },
  {
    id: 'commonsense',
    name: 'Commonsense',
    icon: Lightbulb,
    description: 'Commonsense knowledge base',
    category: 'ai',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/commonsense',
    order: 150,
    keywords: ['facts', 'knowledge', 'common'],
  },
  {
    id: 'transfer',
    name: 'Transfer',
    icon: Share2,
    description: 'Transfer learning',
    category: 'ai',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/transfer',
    order: 151,
    keywords: ['analogy', 'pattern', 'domain'],
  },
  {
    id: 'grounding',
    name: 'Grounding',
    icon: Globe,
    description: 'Embodied cognition grounding',
    category: 'ai',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/grounding',
    order: 152,
    keywords: ['sensor', 'embodied', 'real-world'],
  },
  {
    id: 'experience',
    name: 'Experience',
    icon: BookOpen,
    description: 'Experience learning',
    category: 'ai',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/experience',
    order: 153,
    keywords: ['learn', 'memory', 'pattern'],
  },

  // ── Extensions: Specialized ─────────────────────────────────────
  {
    id: 'lab',
    name: 'Lab',
    icon: FlaskConical,
    description: 'Experimentation sandbox & adjacent reality explorer',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/lab',
    order: 160,
    keywords: ['experiment', 'test', 'sandbox', 'explore', 'adjacent', 'reality'],
  },
  {
    id: 'finance',
    name: 'Finance',
    icon: DollarSign,
    description: 'Financial tools',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/finance',
    order: 161,
    keywords: ['money', 'investment', 'portfolio'],
  },
  {
    id: 'collab',
    name: 'Collab',
    icon: Users,
    description: 'Real-time collaboration',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/collab',
    order: 162,
    keywords: ['collaborate', 'share', 'teamwork'],
  },
  {
    id: 'suffering',
    name: 'Suffering',
    icon: AlertTriangle,
    description: 'Suffering detection monitor',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/suffering',
    order: 163,
    keywords: ['harm', 'pain', 'wellbeing'],
  },
  {
    id: 'invariant',
    name: 'Invariant',
    icon: Shield,
    description: 'System invariant checker',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/invariant',
    order: 164,
    keywords: ['constraint', 'rule', 'check'],
  },
  {
    id: 'fork',
    name: 'Fork',
    icon: GitFork,
    description: 'DTU fork manager',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/fork',
    order: 165,
    keywords: ['branch', 'version', 'copy'],
  },
  {
    id: 'law',
    name: 'Law',
    icon: Scale,
    description: 'Legal and compliance tools',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/law',
    order: 166,
    keywords: ['legal', 'compliance', 'regulation'],
  },
  {
    id: 'legacy',
    name: 'Legacy',
    icon: Clock,
    description: 'Legacy data viewer',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/legacy',
    order: 167,
    keywords: ['old', 'archive', 'historical'],
  },
  {
    id: 'organ',
    name: 'Organ',
    icon: Workflow,
    description: 'Organization tools',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/organ',
    order: 168,
    keywords: ['organize', 'structure'],
  },
  {
    id: 'export',
    name: 'Export',
    icon: Upload,
    description: 'Data export',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/export',
    order: 169,
    keywords: ['download', 'backup'],
  },
  {
    id: 'import',
    name: 'Import',
    icon: Download,
    description: 'Data import',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/import',
    order: 170,
    keywords: ['upload', 'ingest'],
  },
  {
    id: 'custom',
    name: 'Custom',
    icon: Wand2,
    description: 'Custom lens builder',
    category: 'specialized',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/custom',
    order: 999,
    keywords: ['build', 'create', 'configure'],
  },

  // ── Extensions: Super-Lenses (industry domains) ────────────────
  {
    id: 'healthcare',
    name: 'Healthcare',
    icon: Stethoscope,
    description: 'Healthcare & clinical management',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/healthcare',
    order: 200,
    keywords: ['medical', 'clinical', 'patient', 'health'],
  },
  {
    id: 'trades',
    name: 'Trades',
    icon: Wrench,
    description: 'Trades & construction',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/trades',
    order: 201,
    keywords: ['construction', 'plumbing', 'electrical', 'contractor'],
  },
  {
    id: 'food',
    name: 'Food',
    icon: UtensilsCrossed,
    description: 'Food & hospitality',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/food',
    order: 202,
    keywords: ['restaurant', 'recipe', 'catering', 'kitchen'],
  },
  {
    id: 'retail',
    name: 'Retail',
    icon: ShoppingCart,
    description: 'Retail & commerce',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/retail',
    order: 203,
    keywords: ['store', 'inventory', 'pos', 'ecommerce'],
  },
  {
    id: 'household',
    name: 'Household',
    icon: Home,
    description: 'Home & family management',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/household',
    order: 204,
    keywords: ['family', 'home', 'chores', 'maintenance'],
  },
  {
    id: 'accounting',
    name: 'Accounting',
    icon: Calculator,
    description: 'Accounting & finance',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/accounting',
    order: 205,
    keywords: ['bookkeeping', 'invoicing', 'tax', 'payroll'],
  },
  {
    id: 'agriculture',
    name: 'Agriculture',
    icon: Wheat,
    description: 'Agriculture & farming',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/agriculture',
    order: 206,
    keywords: ['farming', 'crops', 'livestock', 'harvest'],
  },
  {
    id: 'logistics',
    name: 'Logistics',
    icon: Truck,
    description: 'Transportation & logistics',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/logistics',
    order: 207,
    keywords: ['shipping', 'fleet', 'warehouse', 'route'],
  },
  {
    id: 'education',
    name: 'Education',
    icon: GraduationCap,
    description: 'Education & learning',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/education',
    order: 208,
    keywords: ['school', 'student', 'course', 'teaching'],
  },
  {
    id: 'legal',
    name: 'Legal',
    icon: Briefcase,
    description: 'Legal & compliance',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/legal',
    order: 209,
    keywords: ['case', 'contract', 'compliance', 'filing'],
  },
  {
    id: 'nonprofit',
    name: 'Nonprofit',
    icon: HeartHandshake,
    description: 'Nonprofit & community',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/nonprofit',
    order: 210,
    keywords: ['donor', 'grant', 'volunteer', 'charity'],
  },
  {
    id: 'realestate',
    name: 'Real Estate',
    icon: Building2,
    description: 'Real estate management',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/realestate',
    order: 211,
    keywords: ['property', 'listing', 'tenant', 'mortgage'],
  },
  {
    id: 'fitness',
    name: 'Fitness',
    icon: Dumbbell,
    description: 'Fitness & wellness',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/fitness',
    order: 212,
    keywords: ['training', 'workout', 'gym', 'wellness'],
  },
  {
    id: 'creative',
    name: 'Creative Production',
    icon: Palette,
    description: 'Creative production',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/creative',
    order: 213,
    keywords: ['photography', 'video', 'design', 'production'],
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing',
    icon: Factory,
    description: 'Manufacturing & production',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/manufacturing',
    order: 214,
    keywords: ['factory', 'assembly', 'quality', 'bom'],
  },
  {
    id: 'environment',
    name: 'Environment',
    icon: TreePine,
    description: 'Environmental & outdoors',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/environment',
    order: 215,
    keywords: ['ecology', 'wildlife', 'conservation', 'sustainability'],
  },
  {
    id: 'government',
    name: 'Government',
    icon: Landmark,
    description: 'Government & public service',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/government',
    order: 216,
    keywords: ['permit', 'public', 'emergency', 'records'],
  },
  {
    id: 'aviation',
    name: 'Aviation',
    icon: Plane,
    description: 'Aviation & maritime',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/aviation',
    order: 217,
    keywords: ['flight', 'pilot', 'vessel', 'charter'],
  },
  {
    id: 'events',
    name: 'Events',
    icon: PartyPopper,
    description: 'Events & entertainment',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/events',
    order: 218,
    keywords: ['venue', 'festival', 'concert', 'production'],
  },
  {
    id: 'science',
    name: 'Science',
    icon: FlaskRound,
    description: 'Science & field work',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/science',
    order: 219,
    keywords: ['expedition', 'lab', 'sample', 'research'],
  },
  {
    id: 'security',
    name: 'Security',
    icon: ShieldCheck,
    description: 'Security operations',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/security',
    order: 220,
    keywords: ['patrol', 'incident', 'surveillance', 'investigation'],
  },
  {
    id: 'services',
    name: 'Services',
    icon: Scissors,
    description: 'Personal services',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/services',
    order: 221,
    keywords: ['salon', 'cleaning', 'daycare', 'appointment'],
  },
  {
    id: 'insurance',
    name: 'Insurance',
    icon: Umbrella,
    description: 'Insurance & risk management',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/insurance',
    order: 222,
    keywords: ['policy', 'claim', 'premium', 'coverage'],
  },

  // ── Lifestyle Lenses (61-68) ─────────────────────────────────────
  {
    id: 'travel',
    name: 'Travel',
    icon: Compass,
    description: 'Trip planning & travel management',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/travel',
    order: 261,
    keywords: ['trip', 'itinerary', 'flight', 'hotel', 'vacation', 'destination'],
  },
  {
    id: 'fashion',
    name: 'Fashion',
    icon: Shirt,
    description: 'Wardrobe & style management',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/fashion',
    order: 262,
    keywords: ['outfit', 'wardrobe', 'style', 'clothing', 'accessories'],
  },
  {
    id: 'cooking',
    name: 'Cooking',
    icon: ChefHat,
    description: 'Recipes, meal prep & kitchen management',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/cooking',
    order: 263,
    keywords: ['recipe', 'meal', 'ingredient', 'kitchen', 'baking'],
  },
  {
    id: 'home-improvement',
    name: 'Home Improvement',
    icon: Hammer,
    description: 'Home renovation & improvement projects',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/home-improvement',
    order: 264,
    keywords: ['renovation', 'repair', 'project', 'contractor', 'remodel'],
  },
  {
    id: 'parenting',
    name: 'Parenting',
    icon: Baby,
    description: 'Parenting, childcare & family',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/parenting',
    order: 265,
    keywords: ['child', 'baby', 'family', 'milestone', 'school'],
  },
  {
    id: 'pets',
    name: 'Pets',
    icon: PawPrint,
    description: 'Pet care & management',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/pets',
    order: 266,
    keywords: ['pet', 'dog', 'cat', 'vet', 'animal', 'care'],
  },
  {
    id: 'sports',
    name: 'Sports',
    icon: Trophy,
    description: 'Sports tracking & team management',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/sports',
    order: 267,
    keywords: ['team', 'game', 'score', 'fitness', 'league', 'training'],
  },
  {
    id: 'diy',
    name: 'DIY',
    icon: Wrench,
    description: 'DIY projects & crafts',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/diy',
    order: 268,
    keywords: ['project', 'craft', 'build', 'tool', 'maker', 'handmade'],
  },

  // ── Social & Community Lenses (76-77) ────────────────────────────
  {
    id: 'debate',
    name: 'Debate',
    icon: Swords,
    description: 'Structured debates & argumentation',
    category: 'governance',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/debate',
    order: 276,
    keywords: ['argument', 'debate', 'pro', 'con', 'discussion', 'position'],
  },
  {
    id: 'mentorship',
    name: 'Mentorship',
    icon: BadgeCheck,
    description: 'Mentorship matching & tracking',
    category: 'governance',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/mentorship',
    order: 277,
    keywords: ['mentor', 'mentee', 'coaching', 'guidance', 'learning'],
  },

  // ── New Cognitive System Lenses ──────────────────────────────────
  {
    id: 'app-maker',
    name: 'App Maker',
    icon: Boxes,
    description: 'Compose apps from existing primitives',
    category: 'system',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/app-maker',
    order: 231,
    keywords: ['app', 'maker', 'compose', 'primitives', 'builder'],
  },

  // ── New Cognitive & Meta Lenses ─────────────────────────────────
  {
    id: 'analytics',
    name: 'Analytics',
    icon: TrendingUp,
    description: 'Platform analytics & usage insights',
    category: 'system',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/analytics',
    order: 232,
    keywords: ['metrics', 'usage', 'insights', 'statistics'],
  },
  {
    id: 'bridge',
    name: 'Bridge',
    icon: Link2,
    description: 'Cross-lens bridge connections',
    category: 'system',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/bridge',
    order: 233,
    keywords: ['connection', 'link', 'cross-lens'],
  },
  {
    id: 'disputes',
    name: 'Disputes',
    icon: Scale,
    description: 'Dispute resolution & mediation',
    category: 'governance',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/disputes',
    order: 278,
    keywords: ['conflict', 'resolution', 'mediation', 'arbitration'],
  },
  {
    id: 'privacy',
    name: 'Privacy',
    icon: ShieldCheck,
    description: 'Privacy controls & data management',
    category: 'governance',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/privacy',
    order: 279,
    keywords: ['gdpr', 'data', 'consent', 'privacy'],
  },
  {
    id: 'wallet',
    name: 'Wallet',
    icon: Wallet,
    description: 'Concord Coin wallet & transactions',
    category: 'governance',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/wallet',
    order: 280,
    keywords: ['coins', 'balance', 'transactions', 'credits'],
  },
  {
    id: 'world',
    name: 'World Lens',
    icon: Globe,
    description:
      'Simulation sandbox — design, validate, and publish physics-bound creations in shared districts',
    category: 'superlens',
    showInSidebar: true,
    showInCommandPalette: true,
    path: '/lenses/world',
    order: 5,
    keywords: [
      'world',
      'simulation',
      'physics',
      'building',
      'district',
      'concordia',
      'materials',
      'engineering',
      'validation',
      'construction',
      'infrastructure',
    ],
  },
  {
    id: 'all',
    name: 'All DTUs',
    icon: Search,
    description: 'Universal search across all lenses',
    category: 'system',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/all',
    order: 234,
    keywords: ['search', 'browse', 'all', 'universal'],
  },

  // ── Unregistered Industry & Professional Lenses ────────────────
  {
    id: 'automotive',
    name: 'Automotive',
    icon: Wrench,
    description: 'Automotive repair & fleet management',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/automotive',
    order: 300,
    keywords: ['car', 'vehicle', 'repair', 'fleet'],
  },
  {
    id: 'carpentry',
    name: 'Carpentry',
    icon: Hammer,
    description: 'Woodworking & carpentry projects',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/carpentry',
    order: 301,
    keywords: ['wood', 'furniture', 'carpentry', 'build'],
  },
  {
    id: 'construction',
    name: 'Construction',
    icon: HardHat,
    description: 'Construction project management',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/construction',
    order: 302,
    keywords: ['building', 'contractor', 'project', 'site'],
  },
  {
    id: 'consulting',
    name: 'Consulting',
    icon: Briefcase,
    description: 'Consulting engagement management',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/consulting',
    order: 303,
    keywords: ['consulting', 'client', 'engagement', 'advisory'],
  },
  {
    id: 'defense',
    name: 'Defense',
    icon: Shield,
    description: 'Defense & national security',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/defense',
    order: 304,
    keywords: ['military', 'defense', 'security', 'intelligence'],
  },
  {
    id: 'electrical',
    name: 'Electrical',
    icon: Plug,
    description: 'Electrical work & systems',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/electrical',
    order: 305,
    keywords: ['electrical', 'wiring', 'power', 'circuits'],
  },
  {
    id: 'emergency-services',
    name: 'Emergency Services',
    icon: AlertTriangle,
    description: 'Emergency response & dispatch',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/emergency-services',
    order: 306,
    keywords: ['emergency', 'fire', 'ems', 'dispatch', 'rescue'],
  },
  {
    id: 'energy',
    name: 'Energy',
    icon: Zap,
    description: 'Energy production & management',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/energy',
    order: 307,
    keywords: ['power', 'solar', 'wind', 'electricity', 'grid'],
  },
  {
    id: 'engineering',
    name: 'Engineering',
    icon: Cog,
    description: 'Engineering design & analysis',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/engineering',
    order: 308,
    keywords: ['engineering', 'design', 'cad', 'structural'],
  },
  {
    id: 'forestry',
    name: 'Forestry',
    icon: TreePine,
    description: 'Forestry & land management',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/forestry',
    order: 309,
    keywords: ['forest', 'timber', 'wildlife', 'conservation'],
  },
  {
    id: 'geology',
    name: 'Geology',
    icon: Mountain,
    description: 'Geological surveys & analysis',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/geology',
    order: 310,
    keywords: ['rocks', 'minerals', 'survey', 'earth'],
  },
  {
    id: 'hr',
    name: 'HR',
    icon: Users,
    description: 'Human resources management',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/hr',
    order: 311,
    keywords: ['hiring', 'employees', 'payroll', 'benefits'],
  },
  {
    id: 'hvac',
    name: 'HVAC',
    icon: Wind,
    description: 'Heating, ventilation & air conditioning',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/hvac',
    order: 312,
    keywords: ['heating', 'cooling', 'ventilation', 'climate'],
  },
  {
    id: 'landscaping',
    name: 'Landscaping',
    icon: TreePine,
    description: 'Landscaping & garden design',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/landscaping',
    order: 313,
    keywords: ['garden', 'landscape', 'plants', 'outdoor'],
  },
  {
    id: 'law-enforcement',
    name: 'Law Enforcement',
    icon: Shield,
    description: 'Law enforcement operations',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/law-enforcement',
    order: 314,
    keywords: ['police', 'investigation', 'patrol', 'crime'],
  },
  {
    id: 'masonry',
    name: 'Masonry',
    icon: Building2,
    description: 'Masonry & stonework',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/masonry',
    order: 315,
    keywords: ['brick', 'stone', 'concrete', 'masonry'],
  },
  {
    id: 'materials',
    name: 'Materials',
    icon: Gem,
    description: 'Materials science & engineering',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/materials',
    order: 316,
    keywords: ['materials', 'composite', 'alloy', 'testing'],
  },
  {
    id: 'mining',
    name: 'Mining',
    icon: Hammer,
    description: 'Mining operations & exploration',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/mining',
    order: 317,
    keywords: ['mine', 'ore', 'extraction', 'drilling'],
  },
  {
    id: 'ocean',
    name: 'Ocean',
    icon: Waves,
    description: 'Marine & ocean sciences',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/ocean',
    order: 318,
    keywords: ['marine', 'ocean', 'maritime', 'nautical'],
  },
  {
    id: 'pharmacy',
    name: 'Pharmacy',
    icon: Pill,
    description: 'Pharmacy & medication management',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/pharmacy',
    order: 319,
    keywords: ['medication', 'prescription', 'drug', 'pharmacy'],
  },
  {
    id: 'plumbing',
    name: 'Plumbing',
    icon: Wrench,
    description: 'Plumbing systems & repair',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/plumbing',
    order: 320,
    keywords: ['pipes', 'plumbing', 'water', 'drainage'],
  },
  {
    id: 'supplychain',
    name: 'Supply Chain',
    icon: Truck,
    description: 'Supply chain management',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/supplychain',
    order: 321,
    keywords: ['supply', 'procurement', 'vendor', 'inventory'],
  },
  {
    id: 'telecommunications',
    name: 'Telecom',
    icon: Radio,
    description: 'Telecommunications & networks',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/telecommunications',
    order: 322,
    keywords: ['telecom', 'network', 'wireless', 'fiber'],
  },
  {
    id: 'urban-planning',
    name: 'Urban Planning',
    icon: MapPin,
    description: 'City planning & zoning',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/urban-planning',
    order: 323,
    keywords: ['city', 'zoning', 'planning', 'infrastructure'],
  },
  {
    id: 'veterinary',
    name: 'Veterinary',
    icon: PawPrint,
    description: 'Veterinary medicine & animal care',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/veterinary',
    order: 324,
    keywords: ['vet', 'animal', 'pet', 'clinic'],
  },
  {
    id: 'welding',
    name: 'Welding',
    icon: Zap,
    description: 'Welding & metalwork',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/welding',
    order: 325,
    keywords: ['weld', 'metal', 'fabrication', 'steel'],
  },
  {
    id: 'desert',
    name: 'Desert',
    icon: Mountain,
    description: 'Desert ecology & arid environments',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/desert',
    order: 326,
    keywords: ['desert', 'arid', 'climate', 'ecology'],
  },

  // ── Unregistered Creative & Knowledge Lenses ───────────────────
  {
    id: 'animation',
    name: 'Animation',
    icon: Play,
    description: 'Animation & motion graphics',
    category: 'creative',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/animation',
    order: 350,
    keywords: ['animate', 'motion', 'video', '2d', '3d'],
  },
  {
    id: 'artistry',
    name: 'Artistry',
    icon: Palette,
    description: 'Advanced artistic techniques',
    category: 'creative',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/artistry',
    order: 351,
    keywords: ['art', 'technique', 'style', 'craft'],
  },
  {
    id: 'creative-writing',
    name: 'Creative Writing',
    icon: PenTool,
    description: 'Fiction, poetry & storytelling',
    category: 'creative',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/creative-writing',
    order: 352,
    keywords: ['writing', 'fiction', 'story', 'narrative'],
  },
  {
    id: 'film-studios',
    name: 'Film Studios',
    icon: Play,
    description: 'Film production & post-production',
    category: 'creative',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/film-studios',
    order: 353,
    keywords: ['film', 'movie', 'production', 'director'],
  },
  {
    id: 'game-design',
    name: 'Game Design',
    icon: Gamepad2,
    description: 'Game design & level editing',
    category: 'creative',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/game-design',
    order: 354,
    keywords: ['gamedev', 'level', 'mechanics', 'design'],
  },
  {
    id: 'photography',
    name: 'Photography',
    icon: Camera,
    description: 'Photography & image editing',
    category: 'creative',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/photography',
    order: 355,
    keywords: ['photo', 'camera', 'edit', 'lightroom'],
  },
  {
    id: 'poetry',
    name: 'Poetry',
    icon: PenTool,
    description: 'Poetry composition & analysis',
    category: 'creative',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/poetry',
    order: 356,
    keywords: ['poem', 'verse', 'rhyme', 'meter'],
  },

  // ── Unregistered Knowledge & Science Lenses ────────────────────
  {
    id: 'astronomy',
    name: 'Astronomy',
    icon: Orbit,
    description: 'Astronomy & celestial observation',
    category: 'science',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/astronomy',
    order: 360,
    keywords: ['stars', 'planets', 'telescope', 'celestial'],
  },
  {
    id: 'atlas',
    name: 'Atlas',
    icon: MapIcon,
    description: 'Geographic atlas & mapping',
    category: 'science',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/atlas',
    order: 361,
    keywords: ['map', 'geography', 'location', 'terrain'],
  },
  {
    id: 'history',
    name: 'History',
    icon: FileText,
    description: 'Historical records & timelines',
    category: 'knowledge',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/history',
    order: 362,
    keywords: ['history', 'event', 'era', 'timeline'],
  },
  {
    id: 'linguistics',
    name: 'Linguistics',
    icon: Globe,
    description: 'Language analysis & translation',
    category: 'knowledge',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/linguistics',
    order: 363,
    keywords: ['language', 'translation', 'grammar', 'syntax'],
  },
  {
    id: 'philosophy',
    name: 'Philosophy',
    icon: Lightbulb,
    description: 'Philosophical frameworks & arguments',
    category: 'knowledge',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/philosophy',
    order: 364,
    keywords: ['philosophy', 'logic', 'argument', 'ethics'],
  },
  {
    id: 'robotics',
    name: 'Robotics',
    icon: Bot,
    description: 'Robotics design & control systems',
    category: 'science',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/robotics',
    order: 365,
    keywords: ['robot', 'automation', 'control', 'servo'],
  },
  {
    id: 'space',
    name: 'Space',
    icon: Rocket,
    description: 'Space exploration & aerospace',
    category: 'science',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/space',
    order: 366,
    keywords: ['space', 'nasa', 'rocket', 'orbit', 'satellite'],
  },

  // ── Unregistered Professional & Social Lenses ──────────────────
  {
    id: 'marketing',
    name: 'Marketing',
    icon: TrendingUp,
    description: 'Marketing campaigns & analytics',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/marketing',
    order: 370,
    keywords: ['campaign', 'seo', 'social', 'brand'],
  },
  {
    id: 'mental-health',
    name: 'Mental Health',
    icon: Heart,
    description: 'Mental wellness & therapy tools',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/mental-health',
    order: 371,
    keywords: ['therapy', 'wellness', 'anxiety', 'counseling'],
  },
  {
    id: 'projects',
    name: 'Projects',
    icon: Layout,
    description: 'Project management & tracking',
    category: 'superlens',
    showInSidebar: false,
    showInCommandPalette: true,
    path: '/lenses/projects',
    order: 372,
    keywords: ['project', 'task', 'milestone', 'gantt'],
  },

  // ── Command Center (sovereign dashboard) ───────────────────────
  {
    id: 'command-center',
    name: 'Command Center',
    icon: Shield,
    description: 'Sovereign command center — brains, repair, attention, forgetting, promotions',
    category: 'system',
    showInSidebar: true,
    showInCommandPalette: true,
    path: '/lenses/command-center',
    order: 6,
    keywords: ['sovereign', 'admin', 'control', 'command', 'center', 'brains', 'repair'],
  },
];

/** Category display configuration */
export const LENS_CATEGORIES: Record<LensCategory, { label: string; color: string }> = {
  core: { label: 'Core', color: 'text-neon-blue' },
  knowledge: { label: 'Knowledge', color: 'text-neon-cyan' },
  science: { label: 'Science', color: 'text-neon-green' },
  creative: { label: 'Creative', color: 'text-neon-pink' },
  governance: { label: 'Governance', color: 'text-neon-purple' },
  ai: { label: 'AI & Cognition', color: 'text-yellow-400' },
  system: { label: 'System', color: 'text-gray-400' },
  specialized: { label: 'Specialized', color: 'text-neon-cyan' },
  superlens: { label: 'Industry Domains', color: 'text-orange-400' },
};

// ── Derived accessors ──────────────────────────────────────────

/** The 5 core lenses for sidebar display. */
export function getCoreLenses(): LensEntry[] {
  return LENS_REGISTRY.filter((l) => CORE_LENS_IDS.has(l.id)).sort((a, b) => a.order - b.order);
}

/** Lenses absorbed into a specific core lens, ordered. */
export function getAbsorbedLenses(coreLensId: CoreLensId): LensEntry[] {
  return LENS_REGISTRY.filter((l) => l.coreLens === coreLensId).sort((a, b) => a.order - b.order);
}

/** Extension lenses — not core and not absorbed into a core lens. */
export function getExtensionLenses(): LensEntry[] {
  return LENS_REGISTRY.filter(
    (l) => !CORE_LENS_IDS.has(l.id) && !l.coreLens && l.id !== 'hub' && l.id !== 'global'
  ).sort((a, b) => a.order - b.order);
}

/** Check if a lens is a core lens */
export function isCoreLens(id: string): boolean {
  return CORE_LENS_IDS.has(id);
}

/** Get the parent core lens for an absorbed lens */
export function getParentCoreLens(lensId: string): CoreLensId | undefined {
  return ABSORPTION_MAP.get(lensId);
}

/** Get core lens config by ID */
export function getCoreLensConfig(id: CoreLensId): CoreLensConfig | undefined {
  return CORE_LENSES.find((c) => c.id === id);
}

/** Lenses visible in the sidebar, ordered. */
export function getSidebarLenses(): LensEntry[] {
  return LENS_REGISTRY.filter((l) => l.showInSidebar).sort((a, b) => a.order - b.order);
}

/** Lenses available in the command palette, ordered. */
export function getCommandPaletteLenses(): LensEntry[] {
  return LENS_REGISTRY.filter((l) => l.showInCommandPalette).sort((a, b) => a.order - b.order);
}

/** All lens IDs — used for build-time route validation. */
export function getAllLensIds(): string[] {
  return LENS_REGISTRY.map((l) => l.id);
}

/** Lookup a lens by id. */
export function getLensById(id: string): LensEntry | undefined {
  return LENS_REGISTRY.find((l) => l.id === id);
}

/** Lenses grouped by category, ordered. */
export function getLensesByCategory(): Record<LensCategory, LensEntry[]> {
  const grouped = {} as Record<LensCategory, LensEntry[]>;
  for (const cat of Object.keys(LENS_CATEGORIES) as LensCategory[]) {
    grouped[cat] = LENS_REGISTRY.filter((l) => l.category === cat).sort(
      (a, b) => a.order - b.order
    );
  }
  return grouped;
}

// ── Sovereign visibility & sidebar category grouping ──────────

/** Lens IDs historically restricted — now open to all authenticated users */
export const SOVEREIGN_LENSES = [] as const;

/** Set for fast lookup (empty — no lenses restricted) */
const SOVEREIGN_LENS_SET = new Set<string>(SOVEREIGN_LENSES);

/**
 * Sidebar category grouping for the "All Lenses" browsable view.
 * Maps human-readable category labels to arrays of lens IDs.
 * This is a flattened presentation-layer grouping, distinct from the
 * data-model `LensCategory` used by LENS_REGISTRY entries.
 */
export const SIDEBAR_CATEGORIES: Record<string, string[]> = {
  Knowledge: [
    'research',
    'hypothesis',
    'reasoning',
    'metacognition',
    'graph',
    'education',
    'science',
    'grounding',
    'commonsense',
    'inference',
    'metalearning',
    'reflection',
    'meta',
    'history',
    'linguistics',
    'philosophy',
    'astronomy',
    'atlas',
    'space',
    'robotics',
    'geology',
    'answers',
    'srs',
    'temporal',
  ],
  Creative: [
    'art',
    'music',
    'creative',
    'studio',
    'whiteboard',
    'game',
    'sim',
    'voice',
    'podcast',
    'animation',
    'artistry',
    'creative-writing',
    'film-studios',
    'game-design',
    'photography',
    'poetry',
    'ar',
    'fractal',
    'genesis',
  ],
  Lifestyle: [
    'food',
    'fitness',
    'healthcare',
    'realestate',
    'travel',
    'daily',
    'calendar',
    'household',
    'insurance',
    'fashion',
    'cooking',
    'home-improvement',
    'parenting',
    'pets',
    'sports',
    'diy',
    'mental-health',
    'eco',
  ],
  Professional: [
    'finance',
    'legal',
    'law',
    'code',
    'database',
    'accounting',
    'billing',
    'logistics',
    'manufacturing',
    'retail',
    'hr',
    'consulting',
    'marketing',
    'projects',
    'engineering',
    'supplychain',
  ],
  'Industry & Trades': [
    'trades',
    'construction',
    'carpentry',
    'electrical',
    'plumbing',
    'hvac',
    'welding',
    'masonry',
    'landscaping',
    'automotive',
    'energy',
    'mining',
    'forestry',
    'materials',
    'ocean',
    'desert',
    'telecommunications',
    'urban-planning',
    'agriculture',
  ],
  'Public & Safety': [
    'government',
    'defense',
    'law-enforcement',
    'emergency-services',
    'veterinary',
    'pharmacy',
    'aviation',
    'environment',
    'nonprofit',
    'events',
    'security',
    'services',
  ],
  Social: [
    'feed',
    'forum',
    'marketplace',
    'collab',
    'vote',
    'global',
    'alliance',
    'debate',
    'mentorship',
    'disputes',
    'privacy',
    'world',
  ],
  'AI & Cognition': [
    'ml',
    'agents',
    'affect',
    'attention',
    'experience',
    'transfer',
    'bio',
    'chem',
    'physics',
    'math',
    'quantum',
    'neuro',
  ],
  Tools: [
    'export',
    'import',
    'fork',
    'analytics',
    'custom',
    'ingest',
    'wallet',
    'bridge',
    'all',
    'app-maker',
    'integrations',
    'repos',
    'schema',
    'debug',
  ],
  System: [
    'chat',
    'entity',
    'council',
    'organ',
    'tick',
    'timeline',
    'queue',
    'resonance',
    'docs',
    'paper',
    'platform',
    'offline',
    'lab',
    'legacy',
    'crypto',
    'invariant',
    'suffering',
    'cri',
    'market',
    'questmarket',
    'ethics',
    'audit',
    'lock',
    'root',
  ],
  Sovereign: ['admin', 'command-center'],
};

/**
 * Returns sidebar categories visible to the given user role.
 * All categories visible to all authenticated users.
 */
export function getVisibleSidebarCategories(_userRole: string): Record<string, string[]> {
  return { ...SIDEBAR_CATEGORIES };
}

/**
 * Determines which sidebar category a lens ID belongs to.
 * Returns 'Other' if the lens isn't in any explicit category.
 */
export function getSidebarCategory(lensId: string): string {
  for (const [category, lenses] of Object.entries(SIDEBAR_CATEGORIES)) {
    if (lenses.includes(lensId)) return category;
  }
  return 'Other';
}

/**
 * Checks if a lens is visible to the given user role.
 * Every lens is visible to all authenticated users. No exceptions.
 */
export function isLensVisible(_lensId: string, _userRole: string): boolean {
  return true;
}

// ── Convenience aliases ─────────────────────────────────────────

/**
 * Lightweight config shape for consumers that only need id/label/category.
 * Compatible with the full LensEntry but smaller surface area.
 */
export interface LensConfig {
  id: string;
  label: string;
  category: string;
  icon?: string;
  sovereignOnly?: boolean;
}

/**
 * Alias for SIDEBAR_CATEGORIES — used by components that reference the
 * "LENS_CATEGORIES" constant name directly.
 */
export { SIDEBAR_CATEGORIES as LENS_CATEGORIES_MAP };

/**
 * Alias for getSidebarCategory — determines which sidebar category a lens belongs to.
 */
export function getLensCategory(lensId: string): string {
  return getSidebarCategory(lensId);
}

/**
 * Alias for getVisibleSidebarCategories — returns categories visible to the role.
 */
export function getVisibleCategories(userRole: string): Record<string, string[]> {
  return getVisibleSidebarCategories(userRole);
}

/**
 * Converts a LensEntry to the lightweight LensConfig shape.
 */
export function toLensConfig(entry: LensEntry): LensConfig {
  return {
    id: entry.id,
    label: entry.name,
    category: getSidebarCategory(entry.id),
    sovereignOnly: SOVEREIGN_LENS_SET.has(entry.id),
  };
}

/**
 * Returns extension lenses grouped by sidebar category for display.
 * Filters by user role (hides sovereign lenses for non-sovereign users).
 * Each category entry contains resolved LensEntry objects.
 */
export function getExtensionsByCategory(
  userRole: string = 'user'
): { category: string; color: string; lenses: LensEntry[] }[] {
  const extensions = getExtensionLenses();
  const visibleCategories = getVisibleSidebarCategories(userRole);

  const result: { category: string; color: string; lenses: LensEntry[] }[] = [];
  const categorized = new Set<string>();

  const categoryColors: Record<string, string> = {
    Knowledge: 'text-neon-cyan',
    Creative: 'text-neon-pink',
    Lifestyle: 'text-neon-green',
    Professional: 'text-neon-blue',
    'Industry & Trades': 'text-amber-400',
    'Public & Safety': 'text-red-300',
    Social: 'text-neon-purple',
    'AI & Cognition': 'text-yellow-400',
    Tools: 'text-emerald-400',
    System: 'text-gray-400',
    Sovereign: 'text-red-400',
    Other: 'text-orange-400',
  };

  for (const [category, lensIds] of Object.entries(visibleCategories)) {
    const idSet = new Set(lensIds);
    const lenses = extensions.filter((l) => {
      if (idSet.has(l.id) && isLensVisible(l.id, userRole)) {
        categorized.add(l.id);
        return true;
      }
      return false;
    });
    if (lenses.length > 0) {
      result.push({ category, color: categoryColors[category] || 'text-gray-400', lenses });
    }
  }

  // Collect uncategorized extensions into "Other"
  const uncategorized = extensions.filter(
    (l) => !categorized.has(l.id) && isLensVisible(l.id, userRole)
  );
  if (uncategorized.length > 0) {
    result.push({ category: 'Other', color: categoryColors['Other'], lenses: uncategorized });
  }

  return result;
}

// ── Sub-Lens Hierarchy ─────────────────────────────────────────
//
// Mirror of the server-side hierarchical registry (see
// server/lib/sub-lens-registry.js). These helpers proxy to the
// /api/sub-lens/* endpoints and are safe to import in client code.

/** A node in the sub-lens tree as returned by /api/sub-lens/tree. */
export interface SubLensTreeNode {
  id: string;
  description?: string;
  children: SubLensTreeNode[];
}

/**
 * Fetches the full sub-lens hierarchy tree from the backend.
 * Returns `[]` on network errors so callers can render gracefully.
 */
export async function getSubLensTree(): Promise<SubLensTreeNode[]> {
  try {
    const r = await fetch('/api/sub-lens/tree');
    if (!r.ok) return [];
    const data = await r.json();
    return Array.isArray(data?.tree) ? (data.tree as SubLensTreeNode[]) : [];
  } catch {
    return [];
  }
}

/**
 * Fetches the children of a given lens id from /api/sub-lens/:lensId/children.
 * Returns `[]` on failure.
 */
export async function getSubLensChildren(lensId: string): Promise<string[]> {
  if (!lensId) return [];
  try {
    const r = await fetch(`/api/sub-lens/${encodeURIComponent(lensId)}/children`);
    if (!r.ok) return [];
    const data = await r.json();
    return Array.isArray(data?.children) ? (data.children as string[]) : [];
  } catch {
    return [];
  }
}
