// server/domains/photography.js
import { callVision, callVisionUrl, visionPromptForDomain } from "../lib/vision-inference.js";

export default function registerPhotographyActions(registerLensAction) {
  registerLensAction("photography", "vision", async (ctx, artifact, _params) => {
    const { imageB64, imageUrl } = artifact.data || {};
    if (!imageB64 && !imageUrl) return { ok: false, error: "imageB64 or imageUrl required" };
    const prompt = visionPromptForDomain("photography");
    return imageUrl ? callVisionUrl(imageUrl, prompt) : callVision(imageB64, prompt);
  });
  registerLensAction("photography", "exposureCalc", (ctx, artifact, _params) => { const data = artifact.data || {}; const iso = parseInt(data.iso) || 100; const aperture = parseFloat(data.aperture) || 5.6; const ev = parseFloat(data.ev) || 12; const shutterSpeed = 1 / (Math.pow(2, ev) * Math.pow(aperture, 2) / (iso * 0.297)); const readable = shutterSpeed >= 1 ? `${Math.round(shutterSpeed)}s` : `1/${Math.round(1/shutterSpeed)}s`; return { ok: true, result: { iso, aperture: `f/${aperture}`, ev, shutterSpeed: readable, depthOfField: aperture <= 2.8 ? "shallow" : aperture <= 8 ? "moderate" : "deep", motionBlur: shutterSpeed > 0.033 ? "likely" : "frozen", handheld: shutterSpeed < 1/(aperture*2) ? "ok" : "use-tripod" } }; });
  registerLensAction("photography", "compositionAnalysis", (ctx, artifact, _params) => { const data = artifact.data || {}; const rules = ["rule-of-thirds","leading-lines","symmetry","framing","depth","negative-space","golden-ratio","patterns"]; const applied = (data.compositionRules || []).filter(r => rules.includes(r.toLowerCase())); return { ok: true, result: { rulesApplied: applied, score: Math.round((applied.length / rules.length) * 100), allRules: rules, suggestions: rules.filter(r => !applied.includes(r)).slice(0,3), strength: applied.length >= 3 ? "strong-composition" : applied.length >= 1 ? "basic-composition" : "no-rules-applied" } }; });
  registerLensAction("photography", "gearRecommend", (ctx, artifact, _params) => { const data = artifact.data || {}; const genre = (data.genre || data.style || "general").toLowerCase(); const budget = (data.budget || "medium").toLowerCase(); const recs = { portrait: { lens: "85mm f/1.8", lighting: "Softbox or natural window light", accessory: "Reflector" }, landscape: { lens: "16-35mm f/4", lighting: "Golden hour", accessory: "Tripod + filters" }, street: { lens: "35mm f/2", lighting: "Available light", accessory: "Small bag" }, macro: { lens: "100mm f/2.8 Macro", lighting: "Ring light", accessory: "Focus rail" }, sports: { lens: "70-200mm f/2.8", lighting: "High ISO capability", accessory: "Monopod" }, general: { lens: "24-70mm f/2.8", lighting: "Speedlight", accessory: "Camera bag" } }; const rec = recs[genre] || recs.general; return { ok: true, result: { genre, budget, recommendation: rec, tip: genre === "portrait" ? "Shoot wide open for creamy bokeh" : genre === "landscape" ? "Use f/8-f/11 for maximum sharpness" : "Practice with what you have" } }; });
  registerLensAction("photography", "printSize", (ctx, artifact, _params) => { const data = artifact.data || {}; const widthPx = parseInt(data.widthPixels) || 4000; const heightPx = parseInt(data.heightPixels) || 3000; const dpi = parseInt(data.dpi) || 300; const widthIn = Math.round(widthPx / dpi * 10) / 10; const heightIn = Math.round(heightPx / dpi * 10) / 10; const megapixels = Math.round(widthPx * heightPx / 1000000 * 10) / 10; const maxPrint = { at300dpi: `${widthIn}" x ${heightIn}"`, at150dpi: `${Math.round(widthPx/150*10)/10}" x ${Math.round(heightPx/150*10)/10}"` }; return { ok: true, result: { resolution: `${widthPx} x ${heightPx}`, megapixels, maxPrintAt300DPI: maxPrint.at300dpi, maxPrintAt150DPI: maxPrint.at150dpi, quality: widthPx >= 4000 ? "professional" : widthPx >= 2000 ? "good" : "web-only" } }; });
}
