// Concord Mobile — DTU Type Bridge
// Maps between mobile domain type codes and server primary/domain type codes.
// Enables cross-platform DTU interoperability.

import { DTU_TYPES } from '../utils/constants';
import type { DTUTypeCode } from '../utils/types';

// Server-side primary type codes (media/content — 0x01-0x0B)
export const SERVER_PRIMARY_TYPES = {
  PLAY_AUDIO: 0x01,
  DISPLAY_IMAGE: 0x02,
  PLAY_VIDEO: 0x03,
  RENDER_DOCUMENT: 0x04,
  RENDER_CODE: 0x05,
  DISPLAY_RESEARCH: 0x06,
  DISPLAY_DATASET: 0x07,
  DISPLAY_3D: 0x08,
  MIXED: 0x09,
  CONDENSED: 0x0A,
  CULTURE: 0x0B,
} as const;

// Server-side domain type codes (semantic/functional — 0x10-0x1F)
export const SERVER_DOMAIN_TYPES = {
  SENSOR_READING: 0x10,
  SHIELD_THREAT: 0x11,
  ECONOMY_TRANSACTION: 0x12,
  IDENTITY_ASSERTION: 0x13,
  MESH_CONTROL: 0x14,
  EMERGENCY_ALERT: 0x15,
  BROADCAST_RELAY: 0x16,
  ATLAS_SIGNAL: 0x17,
  LINEAGE_REF: 0x18,
  GEOSPATIAL: 0x19,
  TIME_SERIES: 0x1A,
  STRUCTURED_KNOWLEDGE: 0x1B,
} as const;

export type ServerTypeCode = number;

// Mobile → Server type mapping
const MOBILE_TO_SERVER: Record<number, ServerTypeCode> = {
  [DTU_TYPES.TEXT]: SERVER_PRIMARY_TYPES.CONDENSED,
  [DTU_TYPES.KNOWLEDGE]: SERVER_PRIMARY_TYPES.CONDENSED,
  [DTU_TYPES.LENS]: SERVER_PRIMARY_TYPES.MIXED,
  [DTU_TYPES.FOUNDATION_SENSE]: SERVER_DOMAIN_TYPES.SENSOR_READING,
  [DTU_TYPES.SHIELD_THREAT]: SERVER_DOMAIN_TYPES.SHIELD_THREAT,
  [DTU_TYPES.ECONOMY_TRANSACTION]: SERVER_DOMAIN_TYPES.ECONOMY_TRANSACTION,
  [DTU_TYPES.IDENTITY_ASSERTION]: SERVER_DOMAIN_TYPES.IDENTITY_ASSERTION,
  [DTU_TYPES.MESH_CONTROL]: SERVER_DOMAIN_TYPES.MESH_CONTROL,
  [DTU_TYPES.EMERGENCY_ALERT]: SERVER_DOMAIN_TYPES.EMERGENCY_ALERT,
  [DTU_TYPES.CREATIVE_WORK]: SERVER_PRIMARY_TYPES.MIXED,
  [DTU_TYPES.ATLAS_SIGNAL]: SERVER_DOMAIN_TYPES.ATLAS_SIGNAL,
  [DTU_TYPES.LINEAGE_REF]: SERVER_DOMAIN_TYPES.LINEAGE_REF,
  [DTU_TYPES.BROADCAST_RELAY]: SERVER_DOMAIN_TYPES.BROADCAST_RELAY,
  [DTU_TYPES.SENSOR_READING]: SERVER_DOMAIN_TYPES.SENSOR_READING,
};

// Server → Mobile type mapping (reverse)
const SERVER_TO_MOBILE: Record<number, DTUTypeCode> = {
  [SERVER_PRIMARY_TYPES.PLAY_AUDIO]: DTU_TYPES.CREATIVE_WORK,
  [SERVER_PRIMARY_TYPES.DISPLAY_IMAGE]: DTU_TYPES.CREATIVE_WORK,
  [SERVER_PRIMARY_TYPES.PLAY_VIDEO]: DTU_TYPES.CREATIVE_WORK,
  [SERVER_PRIMARY_TYPES.RENDER_DOCUMENT]: DTU_TYPES.TEXT,
  [SERVER_PRIMARY_TYPES.RENDER_CODE]: DTU_TYPES.CREATIVE_WORK,
  [SERVER_PRIMARY_TYPES.DISPLAY_RESEARCH]: DTU_TYPES.KNOWLEDGE,
  [SERVER_PRIMARY_TYPES.DISPLAY_DATASET]: DTU_TYPES.KNOWLEDGE,
  [SERVER_PRIMARY_TYPES.DISPLAY_3D]: DTU_TYPES.CREATIVE_WORK,
  [SERVER_PRIMARY_TYPES.MIXED]: DTU_TYPES.CREATIVE_WORK,
  [SERVER_PRIMARY_TYPES.CONDENSED]: DTU_TYPES.TEXT,
  [SERVER_PRIMARY_TYPES.CULTURE]: DTU_TYPES.KNOWLEDGE,
  [SERVER_DOMAIN_TYPES.SENSOR_READING]: DTU_TYPES.FOUNDATION_SENSE,
  [SERVER_DOMAIN_TYPES.SHIELD_THREAT]: DTU_TYPES.SHIELD_THREAT,
  [SERVER_DOMAIN_TYPES.ECONOMY_TRANSACTION]: DTU_TYPES.ECONOMY_TRANSACTION,
  [SERVER_DOMAIN_TYPES.IDENTITY_ASSERTION]: DTU_TYPES.IDENTITY_ASSERTION,
  [SERVER_DOMAIN_TYPES.MESH_CONTROL]: DTU_TYPES.MESH_CONTROL,
  [SERVER_DOMAIN_TYPES.EMERGENCY_ALERT]: DTU_TYPES.EMERGENCY_ALERT,
  [SERVER_DOMAIN_TYPES.BROADCAST_RELAY]: DTU_TYPES.BROADCAST_RELAY,
  [SERVER_DOMAIN_TYPES.ATLAS_SIGNAL]: DTU_TYPES.ATLAS_SIGNAL,
  [SERVER_DOMAIN_TYPES.LINEAGE_REF]: DTU_TYPES.LINEAGE_REF,
};

export function mobileToServerType(mobileType: DTUTypeCode): ServerTypeCode {
  return MOBILE_TO_SERVER[mobileType] ?? SERVER_PRIMARY_TYPES.CONDENSED;
}

export function serverToMobileType(serverType: ServerTypeCode): DTUTypeCode {
  return SERVER_TO_MOBILE[serverType] ?? DTU_TYPES.TEXT;
}

// Cross-domain synthesis compatibility matrix
// Maps which DTU type pairs can produce novel cross-domain insights
export const SYNTHESIS_COMPATIBLE: ReadonlyArray<[DTUTypeCode, DTUTypeCode, string]> = [
  [DTU_TYPES.FOUNDATION_SENSE, DTU_TYPES.KNOWLEDGE, 'empirical_validation'],
  [DTU_TYPES.FOUNDATION_SENSE, DTU_TYPES.ATLAS_SIGNAL, 'ground_truth_verification'],
  [DTU_TYPES.ECONOMY_TRANSACTION, DTU_TYPES.KNOWLEDGE, 'economic_insight'],
  [DTU_TYPES.SHIELD_THREAT, DTU_TYPES.MESH_CONTROL, 'threat_response'],
  [DTU_TYPES.CREATIVE_WORK, DTU_TYPES.KNOWLEDGE, 'creative_scholarship'],
  [DTU_TYPES.SENSOR_READING, DTU_TYPES.EMERGENCY_ALERT, 'environmental_warning'],
  [DTU_TYPES.BROADCAST_RELAY, DTU_TYPES.ATLAS_SIGNAL, 'media_knowledge_synthesis'],
  [DTU_TYPES.TEXT, DTU_TYPES.CREATIVE_WORK, 'narrative_synthesis'],
];

export function canSynthesize(typeA: DTUTypeCode, typeB: DTUTypeCode): string | null {
  for (const [a, b, label] of SYNTHESIS_COMPATIBLE) {
    if ((typeA === a && typeB === b) || (typeA === b && typeB === a)) {
      return label;
    }
  }
  return null;
}
