// Concord Mobile — Utils Barrel Export

// types — re-export all types
export type {
  DTUTypeCode,
  DTUFlagBit,
  TransportLayer,
  DTUHeader,
  DTU,
  DTULineage,
  DTUMeta,
  GeoGrid,
  DeviceIdentity,
  MeshPeer,
  MeshState,
  MeshHealth,
  TransportStatus,
  RelayQueueEntry,
  ConnectionState,
  HeartbeatState,
  SensorReading,
  WiFiScanResult,
  BluetoothEnvironment,
  GPSMultipath,
  SensorType,
  HardwareCapabilities,
  CoinBalance,
  Transaction,
  TransactionType,
  MarketplaceListing,
  ThreatSignature,
  QuarantineEntry,
  ScanResult,
  ThreatMatch,
  LocalModel,
  InferenceRequest,
  InferenceResponse,
  BrainRoutingDecision,
  DTUStoreRow,
  DTUSearchResult,
  DTUStoreStats,
  NDEFDTURecord,
  LoRaConfig,
  LoRaPacket,
  AudioCodecConfig,
  BroadcastConfig,
  BroadcastDTU,
  MeshAuthChallenge,
  MeshAuthResponse,
} from './types';

// constants — re-export all constants
export {
  DTU_HEADER_SIZE,
  DTU_VERSION,
  DTU_MAX_CONTENT_SIZE,
  DTU_HASH_ALGORITHM,
  DTU_HASH_SIZE,
  DTU_GENESIS_SEED_COUNT,
  DTU_HEADER_OFFSETS,
  DTU_TYPES,
  DTU_FLAGS,
  CONCORD_BLE_SERVICE_UUID,
  CONCORD_BLE_DTU_HEADER_CHAR,
  CONCORD_BLE_DTU_CONTENT_CHAR,
  CONCORD_BLE_CONTROL_CHAR,
  BLE_MTU_DEFAULT,
  BLE_SCAN_INTERVAL_MS,
  BLE_DISCOVERY_TIMEOUT_MS,
  WIFI_DIRECT_PORT,
  WIFI_DIRECT_GROUP_TIMEOUT_MS,
  NFC_MAX_PAYLOAD_BYTES,
  LORA_MAX_PACKET_BYTES,
  LORA_DEFAULT_SPREADING_FACTOR,
  DEFAULT_DTU_TTL,
  PRIORITY_DTU_TTL,
  EMERGENCY_DTU_TTL,
  MAX_RELAY_QUEUE_SIZE,
  RELAY_DEDUP_WINDOW_MS,
  HEARTBEAT_INTERVAL_MS,
  HEARTBEAT_LOW_BATTERY_INTERVAL_MS,
  HEARTBEAT_CRITICAL_BATTERY_INTERVAL_MS,
  HEARTBEAT_DORMANT_BATTERY_THRESHOLD,
  FOUNDATION_GEO_GRID_METERS,
  FOUNDATION_MAX_DTUS_PER_DAY,
  FOUNDATION_SENSOR_MAX_DTU_BYTES,
  FOUNDATION_SAMPLING_INTERVAL_MS,
  FOUNDATION_LOW_BATTERY_MULTIPLIER,
  COIN_DECIMALS,
  MIN_TRANSFER_AMOUNT,
  MAX_OFFLINE_TRANSFER_AMOUNT,
  TRANSACTION_NONCE_BYTES,
  IDENTITY_KEY_ALGORITHM,
  IDENTITY_KEY_SIZE,
  IDENTITY_SIGNATURE_SIZE,
  SHIELD_SCAN_BATCH_SIZE,
  SHIELD_QUARANTINE_MAX_SIZE,
  SHIELD_SIGNATURE_VERSION,
  BRAIN_DEFAULT_MODEL_SIZE_MB,
  BRAIN_MAX_CONTEXT_TOKENS,
  BRAIN_INFERENCE_TIMEOUT_MS,
  BRAIN_MAX_MEMORY_MB,
  STORAGE_DTU_PRUNING_AGE_DAYS,
  STORAGE_MAX_APP_SIZE_MB,
  STORAGE_DB_NAME,
  STORAGE_DB_VERSION,
  TRANSPORT_LAYERS,
} from './constants';

// crypto — re-export all functions and types
export {
  crc32,
  toHex,
  fromHex,
  toBase64,
  fromBase64,
  constantTimeEqual,
  generateId,
  encodeUTF8,
  decodeUTF8,
  concatBytes,
  setCryptoProvider,
  getCryptoProvider,
  sha256,
  hmacSha256,
  randomBytes,
} from './crypto';
export type { CryptoProvider } from './crypto';

// hardware-detect — re-export all functions and types
export {
  setNativeDeviceInfo,
  getNativeDeviceInfo,
  detectHardwareCapabilities,
  isCapabilityAvailable,
  getGracefulDegradation,
} from './hardware-detect';
export type { NativeDeviceInfo } from './hardware-detect';
