import { describe, it } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const REPORT = path.join(ROOT, "audit/runtime-crosslayer-coverage.json");

describe("phase-6 crosslayer report", () => {
  it("report exists with all chains passing when present", () => {
    if (!fs.existsSync(REPORT)) {
      return; // generated by npm run capability:coverage:crosslayer
    }
    const report = JSON.parse(fs.readFileSync(REPORT, "utf8"));
    assert.equal(report.phase, "6-crosslayer");
    assert.ok(report.summary.total >= 8);
    assert.equal(report.summary.passed, report.summary.total);
    assert.equal(report.summary.failed, 0);
  });
});
